[#developingwith]
= 使用 Combine 进行开发

通常从利用现有的发布者、操作符和订阅者来组成管道开始。
本书中的许多示例突出了各种模式，其中许多模式旨在对界面内的用户输入提供声明性响应。

你可能还希望创建更容易集成到 Combine 的 API。
例如，创建一个封装远程 API 的发布者，返回单个结果或一系列结果。
或者，你可能正在创建一个订阅者来随着时间的推移去处理和消费数据。

== 关于管道运用的思考

在用 Combine 进行开发时，有两种更广泛的发布者模式经常出现：期望发布者返回单一的值并完成，和期望发布者随着时间的推移返回多个值。

我把第一个称作 “one-shot”（一次性）的发布者或管道。
这些发布者会创建单个响应（或者可能没有响应），然后正常终止。

我把第二个称作 “continuous”（连续）的发布者。
这些发布者和相关管道应始终处于活动状态，并提供处理持续事件的方法。
在这种情况下，管道的寿命要长得多，而且通常不希望此类管道发生失败或终止。

当你在考虑如何使用 Combine 进行开发时，把管道视作这两个类型之一，并把它们混合在一起以实现你的目标，往往是很有帮助的。
例如，模式 <<patterns#patterns-continual-error-handling>> 明确地在不间断的管道中使用一次性的管道来处理错误。

当你创建发布者或管道的实例时，好好思考你希望它如何工作是值得的 —— 要么是一次性的，要么是连续的。
你的选择将关系到你如何处理错误，或者你是否要处理操纵事件时序的操作符 (例如 <<reference#reference-debounce,debounce>> 或者 <<reference#reference-throttle,throttle>>).

除了管道或发布者将提供多少数据外，你还经常需要考虑管道将提供哪种类型对。
许多管道更多的是通过各种类型转换数据，并处理该过程中可能出现的错误情况。
该情况的一个例子是返回一个管道，在管道中如例子 <<patterns#patterns-update-interface-userinput>> 所示返回一个列表，以提供一种表示“空”结果的方法，即使列表中永远不会有超过 1 个元素。

最终，使用 Combine 来连接两端的数据：当数据可用时，由原始的发布者发送它们，然后订阅者最终消费数据。

[#developingwith-types]
== Combine 发布者和订阅者涉及到的 Swift 类型

当你在 Swift 中构建管道时，函数链导致该类型被聚合为嵌套的通用类型。
如果你正在创建一个管道，然后想要将该管道作为 API 提供给代码的另一部分，则对于开发人员来说，暴露的属性或函数的类型定义可能异常复杂且毫无用处。

为了说明暴露的类型复杂性，如果你从 PassthroughSubject 创建了一个发布者，例如：

// Source for this at SwiftUI-NotesTests/CombinePatternTests.swift
[source, swift]
----
let x = PassthroughSubject<String, Never>()
    .flatMap { name in
        return Future<String, Error> { promise in
            promise(.success(""))
            }.catch { _ in
                Just("No user found")
            }.map { result in
                return "\(result) foo"
        }
}
----

结果的类型是：

[source, swift]
----
Publishers.FlatMap<Publishers.Map<Publishers.Catch<Future<String, Error>, Just<String>>, String>, PassthroughSubject<String, Never>>
----

当你想要暴露这个 subject 时，所有这些混合的细节可能会让你感到非常迷惑，使你的代码更难使用。

为了清理该接口，并提供一个好用的 API，可以使用类型擦除类来包装发布者或订阅者。
这样明确隐藏了 Swift 中从链式函数中构建的类型复杂性。

用于为订阅者和发布者暴露简化类型的两个类是：

* https://developer.apple.com/documentation/combine/anysubscriber[AnySubscriber]
* https://developer.apple.com/documentation/combine/anypublisher[AnyPublisher]

每个发布者还继承了一种便利的方法 `eraseToAnyPublisher()`，它返回一个 `AnyPublisher` 实例。
`eraseToAnyPublisher()` 的使用非常像操作符，通常作为链式管道中的最后一个元素，以简化返回的类型。

如果你在上述代码的管道末尾添加 `.eraseToAnyPublisher()`：

[source, swift]
----
let x = PassthroughSubject<String, Never>()
    .flatMap { name in
        return Future<String, Error> { promise in
            promise(.success(""))
            }.catch { _ in
                Just("No user found")
            }.map { result in
                return "\(result) foo"
        }
}.eraseToAnyPublisher()
----

结果的类型将被简化为：

[source, swift]
----
AnyPublisher<String, Never>
----

同样的技术在闭包内构造较小的管道时将非常有用。
例如，当你想在闭包中给操作符 <<reference#reference-flatmap>> 返回一个发布者时，你可以通过明确的声明闭包应返回 `AnyPublisher` 来获得更简单的类型推断。
可以在模式 <<patterns#patterns-sequencing-operations>> 中找到这样的一个例子。

[#developingwith-threads]
== 管道和线程

Combine 不是一个单线程的结构。
操作符和发布者可以在不同的调度队列或 runloops 中运行。
构建的管道可以在单个队列中，也可以跨多个队列或线程传输数据。

Combine 允许发布者指定线程调度器，不论是从上游的发布者（操作符）接收数据或者向下游的订阅者发送数据，都使用它调度到指定线程。
在与更新 UI 元素的订阅者配合使用时，这一点至关重要，因为更新 UI 始终应该在主线程上。

例如，你可能在代码中看到这样的操作符：

[source, swift]
----
.receive(on: RunLoop.main)
----

许多操作符可以修改用于进行相关处理的线程或队列。
<<reference#reference-receive,receive>> 和 <<reference#reference-subscribe,subscribe>> 是最常见的两个，它们分别负责把调用操作符之后和之前的执行代码调度到对应的线程。

许多其他操作符的参数也包括调度器。
例如 <<reference#reference-delay,delay>>, <<reference#reference-debounce,debounce>>, 和 <<reference#reference-throttle,throttle>>.
这些也会对执行代码的队列产生影响 - 无论是对自己，还是对于后续在管道中执行的任何操作符。
这些操作符都使用 `scheduler` 参数，来切换到相应的线程或队列以完成工作。
任何后面连接着他们的操作符也会在其调度器上被调用，从而产生一些影响，如 <<reference#reference-receive,receive>>。

[TIP]
====
如果你想明确指定操作符或后续的操作在哪个线程环境中运行，可以使用 <<reference#reference-receive,receive>>  操作符。
====

== 把 Combine 运用到你的开发中

通常有两种途径使用 Combine 来进行开发：

* 首先，简单的使用是把你闭包中的同步调用改成一个操作符。
最普遍的两个操作符是 <<reference#reference-map,map>> 和 <<reference#reference-trymap,tryMap>>，后者是当你的代码需要抛出错误时使用。

* 第二是集成你自己的代码，即提供完成回调的异步代码或 API。
如果你集成的代码是异步的，则大概无法在闭合内轻松地使用它。
你需要将异步代码包装成一个 Combine 操作符可以配合和调用的结构。
在实践中，这通常意味着需要创建一个发布者的实例，然后在管道中使用它。

<<reference#reference-future,Future>> 发布者是专门用来支持这类集成的, 在模式 <<patterns#patterns-future>> 中有一个这样的示例。

如果你想使用发布者提供的数据作为创建此发布者的参数或输入，则有两种通用的方法可以这么做：

. 使用 <<reference#reference-flatmap,flatMap>> 操作符, 使用传入的数据创建或返回发布者实例。
这是模式 <<patterns#patterns-continual-error-handling>> 的一种变体。

. 或者，<<reference#reference-map,map>> 或 <<reference#reference-trymap,tryMap>> 可被用做创建发布者实例，紧跟 <<reference#reference-switchtolatest,switchToLatest>> 链将该发布者解析为将在管道内传递的值。

<<patterns#patterns-cascading-update-interface>> 和 <<patterns#patterns-update-interface-userinput>> 模式说明了这种使用方法。

你可能会发现创建返回发布者的对象是值得的。
这通常使你的代码能够封装与远程或基于网络的 API 通信的详细信息。
可以使用 <<reference#reference-datataskpublisher,URLSession.dataTaskPublisher>> 或你自己的代码进行开发。
在模式 <<patterns#patterns-cascading-update-interface>> 中详细介绍了这方面的一个简单的示例。

// force a page break - ignored in HTML rendering
<<<
'''
