[#introduction]
= Combine 简介

用 Apple 官方的话来说，Combine 是:

[quote]
a declarative Swift API for processing values over time.

Combine 是 Apple 用来实现函数响应式编程的库， 类似于 https://github.com/ReactiveX/RxSwift[RxSwift]。
RxSwift 是 http://reactivex.io[ReactiveX] 对 Swift 语言的实现。
Combine 使用了许多可以在其他语言和库中找到的相同的函数响应式概念，并将 Swift 的静态类型特性应用其中。

[NOTE]
====
如果你已经熟悉 RxSwift 了，这里有 https://github.com/CombineCommunity/rxswift-to-combine-cheatsheet[一份整理好的表单] 可以让你把 RxSwift 的概念和 API 对应到 Combine 上。
====

== 函数响应式编程

https://en.wikipedia.org/wiki/Functional_reactive_programming[函数响应式编程]， 也称为数据流编程, 建立在 https://en.wikipedia.org/wiki/Functional_programming[函数式编程] 的概念上。
其中函数式编程适用于元素列表，函数响应式编程应用于元素流。
函数式编程中的各种函数，例如 `map`, `filter`, 和 `reduce` 也有可以应用于流的类似函数。
除了函数式编程原本的能力外，函数响应式编程还包括用于分割和合并流的函数。
像函数式编程一样，你可以对在流中的数据进行转换。

在我们编程的系统中有许多部分可以被视为异步信息流 - 事件、对象或数据。
观察者模式监听单个对象，在其更改变化时提供通知事件。
如果你随着时间的推移查看这些通知，它们会构成一个对象流。
函数响应式编程 Combine，允许你创建代码，来描述在流中获取到数据时发生的事情。

你可能希望创建逻辑以监听多个元素的改变。
你可能还希望包含有异步操作的逻辑，其中一些可能会失败。
您可能想要根据时序更改数据流的内容，或更改内容的时序。
处理这些事件流的流程、时序、发生的错误以及协调系统如何响应所有这些事件是函数响应式编程的核心。

基于函数响应式编程的解决方案在开发用户界面时特别有效。
它也更通常用于创建流水线，用来处理从外部源或异步 API 返回的数据。

== Combine 的特性

将这些概念应用于像 Swift 这样的强类型语言是 Apple 在 Combine 中所创造的一部分。
Combine 通过嵌入 back-pressure 来扩展函数响应式编程。
Back-pressure 是指订阅者应该控制它一次获得多少信息以及需要处理多少信息。
这带来了高效的数据操作，并且通过流处理的数据量是可控和可取消的。

Combine 的元素被设置为组合式的，这有利于逐步地集成于现有的代码以采用它。

Apple 的其他一些框架利用了Combine。
SwiftUI 是最受关注的明显示例，同时包含订阅者和发布者。
RealityKit 也具有可用于对事件做出反应的发布者。
Foundation 有许多 Combine 特定的附加功能，包括作为发布者的 NotificationCenter、URLSession 和 Timer。

任何异步 API _都可以_ 与 Combine 一起使用。
例如，你可以使用 Vision 框架中的一些 API，通过利用 Combine 组合流入和流出的数据。

[sidebar]
****
在这本书中，我将把 Combine 中的一系列组合操作称作 **管道**。
管道 也许不是 Apple 在其文档中使用的术语。
****

== 什么情况使用 Combine

当你想要设置对各种输入做出反应时，Combine 最合适，
用户界面也非常适合这种模式。

在用户界面中使用函数响应式编程的经典示例是表单验证，其中用户事件如更改文本字段、点击或鼠标点击 UI 元素构成正在流式传输的数据。
Combine 更进一步，支持监听属性、绑定到对象、从 UI 控件发送和接收更高级别的事件，并支持与几乎所有 Apple 现有 API 生态系统的集成。

你可以使用 Combine 执行的一些操作包括：

* 你可以设置管道以仅在字段中输入的值有效时启用提交按钮。
* 管道还可以执行异步操作（例如检查网络服务）并使用返回的值来选择在视图中更新的方式和内容。
* 管道还可用于对用户在文本字段中动态输入做出反应，并根据他们输入的内容更新用户界面视图。

Combine 不限于用户界面。
任何异步操作序列都可以被作为管道，尤其是当每个步骤的结果流向下一步时。
此类示例可能是一系列网络服务请求，然后对结果进行解码。

Combine 也可用于定义如何处理异步操作中的错误。
通过设置管道并将它们合并在一起，Combine 支持这样做。
Apple 使用 Combine 的示例之一是在本地网络受限时退而求其次地从网络服务获取较低分辨率图像的管道。

你使用 Combine 创建的许多管道都只有少量操作。
即使只进行少量操作，Combine 仍然可以让你更轻松地查看和理解在组合管道时发生的情况。
Combine 的管道是一种声明性方式，用于定义随着时间的推移对数据流中值进行的处理。

// force a page break - ignored in HTML rendering
<<<
'''

[#introduction-appledocs]
== Apple 官方提供的 Combine 文档

icon:apple[size=2x,set=fab]

https://developer.apple.com/documentation/combine[Combine 的在线文档] 可以在 https://developer.apple.com/documentation/combine 找到。
Apple 的开发者文档托管在 https://developer.apple.com/documentation/ 。

=== WWDC 2019 内容

Apple 在其开发者大会中提供了视频、幻灯片和一些示例代码。
关于 Combine 的详细信息主要来自 https://developer.apple.com/videos/play/wwdc2019[WWDC 2019]。

[NOTE]
====
自从在 WWDC 2019 上首次发布以来，Combine 一直在发展。
这些演示文稿中的一些内容现在略有过时或与当前存在的内容有所不同。
这些内容中的大部分对于介绍或了解 Combine 是什么以及可以做什么仍然非常有价值。
====

其中一些介绍并深入讲解了 Combine：

* https://developer.apple.com/videos/play/wwdc2019/722/[Introducing Combine]
** https://devstreaming-cdn.apple.com/videos/wwdc/2019/722l6blhn0efespfgx/722/722_introducing_combine.pdf?dl=1[PDF of presentation notes]

* https://developer.apple.com/videos/play/wwdc2019/721/[Combine in Practice]
** https://devstreaming-cdn.apple.com/videos/wwdc/2019/721ga0kflgr4ypfx/721/721_combine_in_practice.pdf?dl=1[PDF of presentation notes]

许多其他 WWDC19 会议提到了 Combine：

* https://developer.apple.com/videos/play/wwdc2019/415/[Modern Swift API Design]
* https://developer.apple.com/videos/play/wwdc2019/226[Data Flow Through SwiftUI]
* https://developer.apple.com/videos/play/wwdc2019/711[Introducing Combine and Advances in Foundation]
* https://developer.apple.com/videos/play/wwdc2019/712/[Advances in Networking, Part 1]

* https://developer.apple.com/videos/play/wwdc2019/610/[Building Collaborative AR Experiences]
* https://developer.apple.com/videos/play/wwdc2019/223/[Expanding the Sensory Experience with Core Haptics]

== 其他线上的 Combine 资源

除了 Apple 的文档之外，还有许多其他在线资源，你可以在其中找到有关 Combine 运作方式的问题、答案、讨论和说明。

* https://forums.swift.org/[Swift 论坛]（托管于 https://swift.org/[swift 开源项目]）有一个 https://forums.swift.org/tags/combine[combine tag] 有许多有趣讨论。虽然 Combine 框架 *不是* 开源的，但在这些论坛中有它的一些实现和细节的讨论。

* https://stackoverflow.com[Stackoverflow] 也有大量（并且还在不断增加）的 https://stackoverflow.com/questions/tagged/combine[Combine 相关问答]。

// force a page break - ignored in HTML rendering
<<<
