[#patterns-notificationcenter]
== 响应 NotificationCenter 的更新

__目的__::

* 作为发布者接收 NotificationCenter 的通知，以声明式的对所提供的信息做出响应。

__参考__::

* <<reference#reference-notificationcenter,NotificationCenter>>

__另请参阅__::

* 单元测试在 https://github.com/heckj/swiftui-notes/blob/master/UsingCombineTests/NotificationCenterPublisherTests.swift[`UsingCombineTests/NotificationCenterPublisherTests.swift`]

__代码和解释__::

大量的框架和用户界面组件通过 NotificationCenter 的通知提供有关其状态和交互的信息。
Apple 的文档包括一篇关于 https://developer.apple.com/documentation/combine/receiving_and_handling_events_with_combine[receiving and handling events with Combine] 的文章，特别提及了 NotificationCenter。

通过 https://developer.apple.com/documentation/foundation/notificationcenter[NotificationCenter] 发送的 https://developer.apple.com/documentation/foundation/notification[Notifications] 为你应用中的事件提供了一个通用的中心化的位置。

你还可以将自己的通知添加到你的应用程序中，在发送通知时，还可以在其 `userInfo` 属性中添加一个额外的字典来发送数据。
一个定义你自己通知的示例 `.myExampleNotification`：

[source, swift]
----
extension Notification.Name {
    static let myExampleNotification = Notification.Name("an-example-notification")
}
----

通知名称是基于字符串的结构体。
当通知发布到 NotificationCenter 时，可以传递对象引用，表明发送通知的具体对象。
此外，通知可以包括 `userInfo`，是一个 `[AnyHashable : Any]?` 类型的值。
这允许将任意的字典（无论是引用类型还是值类型）包含在通知中。

[source, swift]
----
let myUserInfo = ["foo": "bar"]

let note = Notification(name: .myExampleNotification, userInfo: myUserInfo)
NotificationCenter.default.post(note)
----

[NOTE]
====
虽然在 AppKit 和 macOS 应用程序中普遍地使用了通知，但并非所有开发人员都乐于大量使用 NotificationCenter。
通知起源于更具动态性的 Objective-C runtime ，广泛利用 Any 和 optional 类型。
在 Swift 代码或管道中使用它们意味着管道必须提供类型检查并处理与预期或非预期的数据相关的任何可能错误。
====

创建 NotificationCenter 发布者时，你提供要接收的通知的名称，并可选地提供对象引用，以过滤特定类型的对象。
属于 https://developer.apple.com/documentation/appkit/nscontrol[NSControl] 子类的多个 AppKit 组件共享了一组通知，过滤操作对于获得这些组件的正确的通知至关重要。

订阅 AppKit 生成通知的示例：

[source, swift]
----
let sub = NotificationCenter.default.publisher(for: NSControl.textDidChangeNotification, <1>
                                               object: filterField) <2>
    .map { ($0.object as! NSTextField).stringValue }  <3>
    .assign(to: \MyViewModel.filterString, on: myViewModel) <4>
----
<1> AppKit 中的 TextField 在值更新时生成 `textDidChangeNotification` 通知。
<2> 一个 AppKit 的应用程序通常可以具有大量可能被更改的 TextField。
包含对发送控件的引用可用于过滤你特别感兴趣的文本的更改通知。
<3> <<reference#reference-map,map>> 操作符可用于获取通知中包含的对象引用，在这个例子中，发送通知的 TextField 的 `.stringValue` 属性提供了它更新后的值。
<4> 由此产生的字符串可以使用可写入的 `KeyValue` 路径进行 assign。

一个订阅你自己的通知事件的示例：
[source, swift]
----
let cancellable = NotificationCenter.default.publisher(for: .myExampleNotification, object: nil)
    // can't use the object parameter to filter on a value reference, only class references, but
    // filtering on 'nil' only constrains to notification name, so value objects *can* be passed
    // in the notification itself.
    .sink { receivedNotification in
        print("passed through: ", receivedNotification)
        // receivedNotification.name
        // receivedNotification.object - object sending the notification (sometimes nil)
        // receivedNotification.userInfo - often nil
    }
----

// force a page break - in HTML rendering is just a <HR>
<<<
'''
