[#coreconcepts]
= Core Concepts

[#core-publisher-subscriber]
== Publisher, Subscriber

Two key concepts, described in swift with protocols, are https://developer.apple.com/documentation/combine/publisher[*publisher*] and https://developer.apple.com/documentation/combine/subscriber[*subscriber*].

A publisher fundamentally provides data, when available, upon request.
It is described with two associated types: one for Output and one for Failure.
A subscriber requests data.
It is also described with two associated types, one for Input and one for Failure.

Publishers and subscribers are meant to be connected, and make up the core of Combine.
When you connect a subscriber to a publisher, both types must match: Output to Input, and Failure to Failure.
You can view this as a series of operations on two types in parallel.

//TODO(heckj) - convert to a diagram
[source]
----
Publisher source       Subscriber
+--------------+      +--------------+
|        <Output> --> <Input>        |
|       <Failure> --> <Failure>      |
+--------------+      +--------------+
----

Operators are classes that adopt both the https://developer.apple.com/documentation/combine/subscriber[Subscriber protocol] and https://developer.apple.com/documentation/combine/publisher[Publisher protocol].
They support subscribing to a publisher, and sending results to any subscribers.

You can create chains of these together, for processing, reacting, and transforming the data provided by a publisher, and requested by the subscriber.

I'm calling these composed sequences **pipelines**.

//TODO(heckj) - convert to a diagram
[source]
----
Publisher source       Operator                          Subscriber
+--------------+      +---------------------------+      +--------------+
|        <Output> --> <Input>      map      <Output> --> <Input>        |
|       <Failure> --> <Failure>  function  <Failure> --> <Failure>      |
+--------------+      +---------------------------+      +--------------+
----


Operators can be used to transform types - both the Output and Failure type.
Operators may also split or duplicate streams, or merge streams together.
Operators must always be aligned by the combination of Output/Failure types.
The compiler will enforce the matching types, so getting it wrong will result in a compiler error (and sometimes a useful _fixit_ snippet.)

A simple pipeline, using Combine, might look like:
[source, swift]
----
let _ = Just(5) <1>
    .map { value -> String in <2>
        // do something with the incoming value here
        // and return a string
        return "a string"
    }
    .sink { receivedValue in <3>
        // sink is the subscriber and terminates the pipeline
        print("The end result was \(receivedValue)")
    }
----

<1> The pipeline starts with the publisher `Just`, which responds with the value that its defined with (in this case, the Integer `5`). The output type is <Integer>, and the failure type is <Never>.
<2> the pipeline then has a `map` operator, which is transforming the value. In this example it is ignoring the published input and returning a string. This is also transforming the output type to <String>, and leaving the failure type still set as <Never>
<3> The pipeline then ends with a `sink` subscriber.

When you are viewing a pipeline, or creating one, you can think of it as a sequence of operations linked by the types.
This pattern will come in handy when you start constructing your own pipelines.
When creating pipelines, you are often selecting operators to help you transform the types, to achieve your end goal.
That end goal might be enabling or disabling a user interface element, or it might be retrieving some piece of data to be displayed.

Many combine operators are specifically created to help with these transformations.
Some operators require conformance to an input or failure type.
Other operators may change either or both the failure and output types.
For example, there are a number of operators that have a similar operator prefixed with `try`, which indicates they return an <Error> failure type.

An example of this is <<reference.adoc#reference-map,map>> and <<reference.adoc#reference-trymap,tryMap>>.
The `map` operator allows for any combination of Output and Failure type and passes them through.
`tryMap` accepts any Input, Failure types, and allows any Output type, but will always output an `<Error>` failure type.

Operators like `map` allow you to define the output type being returned by infering the type based on what you return in a closure provided to the operator.
In the example above, the `map` operator is returning a String output type since that it what the closure returns.

To illustrate the example of changing types more concretely, we expand upon the logic to use the values being passed. This example still starts with a publisher providing the types `<Int>`, `<Never>` and end with a subscription taking the types `<String>`, `<Never>`.

// NOTE: source in project at SwiftUI-NotesTests/CombinePatternTests.swift
[source, swift]
----
let _ = Just(5) <1>
    .map { value -> String in <2>
        switch value {
        case _ where value < 1:
            return "none"
        case _ where value == 1:
            return "one"
        case _ where value == 2:
            return "couple"
        case _ where value == 3:
            return "few"
        case _ where value > 8:
            return "many"
        default:
            return "some"
        }
    }
    .sink { receivedValue in <3>
        print("The end result was \(receivedValue)")
    }
----
<1> Just is a publisher that creates an `<Int>`, `<Never>` type combination, provides a single value and then completes.
<2> the closure provided to the `.map()` function takes in an `<Int>` and transforms it into a `<String>`. Since the failure type of <Never> is not changed, it is passed through.
<3> `sink`, the subscriber, receives the `<String>`, `<Never>` combination.


[sidebar]
****
When you are creating pipelines in Xcode and don't match the types, the error message from Xcode may include a helpful _fixit_.
In some cases, such as the example above, the compiler is unable to infer the return types of closure provided to `map` without specifying the return type.
Xcode (11 beta 2 and beta 3) displays this as the error message: `Unable to infer complex closure return type; add explicit type to disambiguate`.
In the example above, we explicitly specified the type being returned with the line `value -> String in`.
****

You can view Combine publishers, operators, and subscribers as having two parallel types that both need to be aligned - one for the functional case and one for the error case.
Designing your pipeline is frequently choosing how to convert one or both of those types and the associated data with it.

More examples, and some common tasks, are detailed in the <<patterns.adoc#patterns,section on patterns>>.

// force a page break - ignored in HTML rendering
<<<

[#coreconcepts-lifecycle]
== Lifecycle of Publishers and Subscribers

Combine is designed such that the subscriber ultimately controls the flow of data, and any related processing that happens in pipelines.
The term commonly used for this is *back-pressure*.

This means that the subscriber provides information for how much information it wants or can accept.
When a subscriber is connected to a publisher, it requests data based with a specific https://developer.apple.com/documentation/combine/subscribers/demand[Demand].

This request it drives calling all the closures up the composed pipeline, and returning any data available from publishers.

With subscribers driving the process, it also allows Combine to support cancellation.
Subscribers all conform to the https://developer.apple.com/documentation/combine/cancellable[Cancellable] protocol.
This means they all have a function `cancel()` that can be invoked to terminate a pipeline.

The end to end lifecycle is enabled by subscribers and publishers communicating in a well defined sequence:

. When the subscriber is attached to a publisher, it starts with a call to `.subscribe(Subscriber)`.
. The publisher in turn acknowledges the subscription calling `receive(subscription)`.

** After the subscription has been acknowledged, the subscriber requests _N_ values with `request(_ : Demand)`.
** The publisher may then (as it has values) sending _N_ (or fewer) values: `receive(_ : Input)`.
A publisher should never send **more** than the demand requested.
** Also after the subscription has been acknowledged, the subscriber can send a https://developer.apple.com/documentation/combine/subscribers/completion[cancellation] with `.cancel()`

. A publisher may optionally send https://developer.apple.com/documentation/combine/subscribers/completion[completion]: `receive(completion:)` which is also how errors are propogated.

[#core-publishers]
== Publishers

The publisher is the provider of data.
The https://developer.apple.com/documentation/combine/publisher[publisher protocol] has a strict contract returning values when asked from subscribers, and possibly terminating with an explicit completion enumeration.

<<reference.adoc#reference-just,Just>> and <<reference.adoc#reference-future,Future>> are extremely common sources to start your own publisher from a value or function.

Many publishers will immediately provide data when requested by a subscriber.
In some cases, a publisher may have a separate mechanism to enable it to return data.
This is codified by the protocol https://developer.apple.com/documentation/combine/connectablepublisher[ConnectablePublisher].
A publisher conforming to `ConnectablePublisher` will have an additional mechanism to start the flow of data after a subscriber has provided a request.
This could be `.autoconnect()`, which will start the flow of data as soon as a subscriber requests it.
The other option is a separate `.connect()` call on the publisher itself.

Combine provides a number of additional convenience publishers:

//TODO(heckj) - convert to xref to reference sections on these operators
[cols="3*^"]
|===
| <<reference.adoc#reference-just,Just>>
| <<reference.adoc#reference-future,Future>>
| <<reference.adoc#reference-published,@Published>>

| <<reference.adoc#reference-empty,Empty>>
| <<reference.adoc#reference-sequence,Sequence>>
| <<reference.adoc#reference-fail,Fail>>

| <<reference.adoc#reference-deferred,Deferred>>
| <<reference.adoc#reference-observableobjectpublisher,ObservableObjectPublisher>>
|

|===

A number of Apple APIs outside of Combine provide publishers as well.

* SwiftUI provides https://developer.apple.com/documentation/swiftui/observedobject[`@ObservedObject`] which can be used to create a publisher.

* Foundation
** <<reference.adoc#reference-datataskpublisher,URLSession.dataTaskPublisher>>
** <<reference.adoc#reference-kvo-publisher,.publisher on KVO instance>>
** <<reference.adoc#reference-notificationcenter,NotificationCenter>>
** <<reference.adoc#reference-timer,Timer>>

[#core-operators]
== Operators

Operators are a convenient name for a number of pre-built functions that are included under Publisher in Apple's reference documentation.
These functions are all meant to be composed into pipelines.
Many will accept  one of more closures from the developer to define the business logic of the operator, while maintaining the adherance to the publisher/subscriber lifecycle.

Some operators support bringing together outputs from different pipelines, or splitting to send to multiple subscribers.
Operators may also have constraints on the types they will operate on.
Operators can also help with error handling and retry logic, buffering and prefetch, controlling timing, and supporting debugging.

[cols="3*^"]
|===
3+h| Mapping elements
| <<reference.adoc#reference-scan,scan>>
| <<reference.adoc#reference-tryscan,tryScan>>
| <<reference.adoc#reference-setfailuretype,setFailureType>>

| <<reference.adoc#reference-map,map>>
| <<reference.adoc#reference-trymap,tryMap>>
| <<reference.adoc#reference-flatmap,flatMap>>
|===

[cols="3*^"]
|===
3+h| Filtering elements
| <<reference.adoc#reference-compactmap,compactMap>>
| <<reference.adoc#reference-trycompactmap,tryCompactMap>>
| <<reference.adoc#reference-replaceempty,replaceEmpty>>

| <<reference.adoc#reference-filter,filter>>
| <<reference.adoc#reference-tryfilter,tryFilter>>
| <<reference.adoc#reference-replaceerror,replaceError>>

| <<reference.adoc#reference-removeduplicates,removeDuplicates>>
| <<reference.adoc#reference-tryremoveduplicates,tryRemoveDuplicates>>
|
|===


[cols="3*^"]
|===
3+h| Reducing elements
| <<reference.adoc#reference-collect,collect>>
| <<reference.adoc#reference-collectbycount,collectByCount>>
| <<reference.adoc#reference-collectbytime,collectByTime>>

| <<reference.adoc#reference-reduce,reduce>>
| <<reference.adoc#reference-tryreduce,tryReduce>>
| <<reference.adoc#reference-ignoreoutput,ignoreOutput>>
|===

[cols="3*^"]
|===
3+h| Mathematic opertions on elements
| <<reference.adoc#reference-comparison,comparison>>
| <<reference.adoc#reference-trycomparison,tryComparison>>
| <<reference.adoc#reference-count,count>>
|===

[cols="3*^"]
|===
3+h| Applying matching criteria to elements
| <<reference.adoc#reference-allsatisfy,allSatisfy>>
| <<reference.adoc#reference-tryallsatisfy,tryAllSatisfy>>
| <<reference.adoc#reference-contains,contains>>

| <<reference.adoc#reference-containswhere,containsWhere>>
| <<reference.adoc#reference-trycontainswhere,tryContainsWhere>>
|
|===

[cols="3*^"]
|===
3+h| Applying sequence operations to elements
| <<reference.adoc#reference-firstwhere,firstWhere>>
| <<reference.adoc#reference-tryfirstwhere,tryFirstWhere>>
| <<reference.adoc#reference-first,first>>

| <<reference.adoc#reference-lastwhere,lastWhere>>
| <<reference.adoc#reference-trylastwhere,tryLastWhere>>
| <<reference.adoc#reference-last,last>>

| <<reference.adoc#reference-dropwhile,dropWhile>>
| <<reference.adoc#reference-trydropwhile,tryDropWhile>>
| <<reference.adoc#reference-dropuntiloutput,dropUntilOutput>>

| <<reference.adoc#reference-concatenate,concatenate>>
| <<reference.adoc#reference-drop,drop>>
| <<reference.adoc#reference-prefixuntiloutput,prefixUntilOutput>>

| <<reference.adoc#reference-prefixwhile,prefixWhile>>
| <<reference.adoc#reference-tryprefixwhile,tryPrefixWhile>>
| <<reference.adoc#reference-output,output>>
|===

[cols="3*^"]
|===
3+h| Combining elements from multiple publishers
| <<reference.adoc#reference-combinelatest,combineLatest>>
| <<reference.adoc#reference-merge,merge>>
| <<reference.adoc#reference-zip,zip>>
|===

[cols="3*^"]
|===
3+h| Handling errors
| <<reference.adoc#reference-catch,catch>>
| <<reference.adoc#reference-trycatch,tryCatch>>
| <<reference.adoc#reference-assertnofailure,assertNoFailure>>

| <<reference.adoc#reference-retry,retry>>
| <<reference.adoc#reference-maperror,mapError>>
|
|===

[cols="3*^"]
|===
3+h| Adapting publisher types
| <<reference.adoc#reference-switchtolatest,switchToLatest>>
| <<reference.adoc#reference-erasetoanypublisher,eraseToAnyPublisher>>
|
|===

[cols="3*^"]
|===
3+h| Controlling timing
| <<reference.adoc#reference-debounce,debounce>>
| <<reference.adoc#reference-delay,delay>>
| <<reference.adoc#reference-measureinterval,measureInterval>>

| <<reference.adoc#reference-throttle,throttle>>
| <<reference.adoc#reference-timeout,timeout>>
|
|===

[cols="3*^"]
|===
3+h| Encoding and decoding
| <<reference.adoc#reference-encode,encode>>
| <<reference.adoc#reference-decode,decode>>
|
|===

[cols="3*^"]
|===
3+h| Working with multiple subscribers
| <<reference.adoc#reference-multicast,multicast>>
|
|
|===

[cols="3*^"]
|===
3+h| Debugging
| <<reference.adoc#reference-breakpoint,breakpoint>>
| <<reference.adoc#reference-handleevents,handleEvents>>
| <<reference.adoc#reference-print,print>>
|===

[#core-subjects]
== Subjects

Subjects are a special case of publisher that also adhere to the https://developer.apple.com/documentation/combine/subject[`subject`] protocol.
This protocol requires subjects to have a `.send()` method to allow the developer to send specific values to a subscriber (or pipeline).

Subjects can be used to "inject" values into a stream, by calling the subject's `.send()` method.
This is useful for integrating existing imperative code with Combine.

A subject can also broadcast values to multiple subscribers.
If multiple subscribers are connected to a subject, it will fanning out values to the multiple subscribers when `send()` is invoked.
A subject is also frequently used to connect or cascade multiple pipelines together, especially to fan out to multiple pipelines.

A subject does not blindly pass through the demand from its subscribers, instead it provides a sort of aggregation point for demand.
A subject will not signal for demand to its connected publishers until it has received at least one subscriber itself.
When it receives any demand, it then signals for `unlimited` demand to connected publishers.
With the subject supporting multiple subscribers, any subscribers that have not requested data with a demand are not provided the data until they do.

There are two types of built-in subjects with Combine: <<reference.adoc#reference-currentvaluesubject,currentValueSubject>> and <<reference.adoc#reference-passthroughsubject,passthroughSubject>>.
They act similiarly, the primary difference being currentValueSubject remembers and provides an initial state value for any subscribers, where passthroughSubject does not.
Both will provide updated values to any subscribers when `.send()` is invoked.

Both CurrentValueSubject and PassthroughSubject are also useful for creating publishers from objects conforming to the
https://developer.apple.com/documentation/combine/observableobject[`ObservableObject`].
This protocol is supported by a number of declarative components within SwiftUI.

[#core-subscribers]
== Subscribers

While https://developer.apple.com/documentation/combine/subscriber[`subscriber`] is the protocol used to receive data throughout a pipeline, _the Subscriber_ typically refers to the end of a pipeline.

There are two subscribers built-in to Combine: <<reference.adoc#reference-assign,assign>> and <<reference.adoc#reference-sink,sink>>.

Subscribers can support cancellation, which terminates a subscription and shuts down all the stream processing prior to any Completion sent by the publisher.
Both `Assign` and `Sink` conform to the https://developer.apple.com/documentation/combine/cancellable[cancellable protocol].

https://developer.apple.com/documentation/combine/subscribers/assign[`assign`] applies values passed down from the publisher to an object defined by a keypath.
The keypath is set when the pipeline is created.
An example of this in swift might look like:

[source, swift]
----
.assign(to: \.isEnabled, on: signupButton)
----

https://developer.apple.com/documentation/combine/subscribers/sink[`sink`] accepts a closure that receives any resulting values from the publisher.
This allows the developer to terminate a pipeline with their own code.
This subscriber is also extremely helpful when writing unit tests to validate either publishers or pipelines.
An example of this in swift might look like:

[source, swift]
----
.sink { receivedValue in
    print("The end result was \(String(describing: receivedValue))")
}
----

Most other subscribers are part of other Apple frameworks.
For example, nearly every control in SwiftUI can act as a subscriber.
The https://developer.apple.com/documentation/swiftui/view/[View protocol] in SwiftUI defines an `.onReceive(publisher)` function to use views as a subscriber.
The `onReceive` function takes a closure akin to `sink` that can manipulate `@State` or `@Bindings` within SwiftUI.

An example of that in SwiftUI might look like:

[source, swift]
----
struct MyView : View {

    @State private var currentStatusValue = "ok"
    var body: some View {
        Text("Current status: \(currentStatusValue)")
    }
    .onReceive(MyPublisher.currentStatusPublisher) { newStatus in
        self.currentStatusValue = newStatus
    }
}
----

For any type of UI object (UIKit, AppKit, or SwiftUI), <<reference.adoc#reference-assign,assign>> can be used with pipelines to manipulate properties.

When you are storing a reference to your own subscriber in order to clean up later, you generally want a reference to cancel the subscription.
<<reference.adoc#reference-anycancellable,anyCancellable>> provides a type-erased reference that converts any subscriber to the type AnyCancellable, allowing the use of `.cancel()` on that reference, but not access to the subscription itself (which could, for instance, request more data).

// force a page break - ignored in HTML rendering
<<<
'''
