[#coreconcepts]
= Core Concepts

[#core-publisher-subscriber]
== Publisher, Subscriber

Two key concepts, described in swift with protocols, are https://developer.apple.com/documentation/combine/publisher[*publisher*] and https://developer.apple.com/documentation/combine/subscriber[*subscriber*].

A publisher provides data.
It is described with two associated types: one for Output and one for Failure.
A subscriber requests data.
It is also described with two associated types, one for Input and one for Failure.
When you connect a subscriber to a publisher, both types must match: Output to Input, and Failure to Failure.
You can view this as a series of operations on two types in parallel.

//TODO(heckj) - convert to a diagram
[source]
----
Publisher source       Subscriber
+--------------+      +--------------+
|        <Output> --> <Input>        |
|       <Failure> --> <Failure>      |
+--------------+      +--------------+
----

Operators are classes that adopt both the https://developer.apple.com/documentation/combine/subscriber[Subscriber protocol] and https://developer.apple.com/documentation/combine/publisher[Publisher protocol].
They support subscribing to a publisher, and sending results to any subscribers.

You can create chains of these together, for processing, reacting, and transforming the data provided by a publisher, and requested by the subscriber.

I'm calling these composed sequences **pipelines**.

//TODO(heckj) - convert to a diagram
[source]
----
Publisher source       Operator                          Subscriber
+--------------+      +---------------------------+      +--------------+
|        <Output> --> <Input>      map      <Output> --> <Input>        |
|       <Failure> --> <Failure>  function  <Failure> --> <Failure>      |
+--------------+      +---------------------------+      +--------------+
----


Operators can be used to transform types - both the Output and Failure type.
Operators may also split or duplicate streams, or merge streams together.
Operators must always be aligned by the combination of Output/Failure types.
The compiler will enforce the matching types, so getting it wrong will result in a compiler error (and sometimes a useful _fixit_ snippet.)

A simple pipeline, using Combine, might look like:
[source, swift]
----
let _ = Just(5) <1>
    .map { value -> String in <2>
        // do something with the incoming value here
        // and return a string
        return "a string"
    }
    .sink { receivedValue in <3>
        // sink is the subscriber and terminates the pipeline
        print("The end result was \(receivedValue)")
    }
----

<1> The pipeline starts with the publisher `Just`, which responds with the value that its defined with (in this case, the Integer `5`). The output type is <Integer>, and the failure type is <Never>.
<2> the pipeline then has a `map` operator, which is transforming the value. In this example it is ignoring the published input and returning a string. This is also transforming the output type to <String>, and leaving the failure type still set as <Never>
<3> The pipeline then ends with a `sink` subscriber.

When you are viewing a pipeline, or creating one, you can think of it as a sequence of operations linked by the types.
This pattern will come in handy when you start constructing your own pipelines.
When creating pipelines, you are often selecting operators to help you transform the types, to achieve your end goal.
That end goal might be enabling or disabling a user interface element, or it might be retrieving some piece of data to be displayed.

Many combine operators are specifically created to help with these transformations.
Some operators require conformance to an input or failure type.
Other operators may change either or both the failure and output types.
For example, there are a number of operators that have a similar operator prefixed with `try`, which indicates they return an <Error> failure type.

An example of this is <<reference.adoc#reference-map>> and <<reference.adoc#reference-tryMap>>.
The `map` operator allows for any combination of Output and Failure type and passes them through.
`tryMap` accepts any Input, Failure types, and allows any Output type, but will always output an `<Error>` failure type.

Operators like `map` allow you to define the output type being returned by infering the type based on what you return in a closure provided to the operator.
In the example above, the `map` operator is returning a String output type since that it what the closure returns.

To illustrate the the example of changing types more concretely, we expand upon the logic to use the values being passed. This example still starts with a publisher providing the types `<Int>`, `<Never>` and end with a subscription taking the types `<String>`, `<Never>`.

// NOTE: source in project at SwiftUI-NotesTests/CombinePatternTests.swift
[source, swift]
----
let _ = Just(5) <1>
    .map { value -> String in <2>
        switch value {
        case _ where value < 1:
            return "none"
        case _ where value == 1:
            return "one"
        case _ where value == 2:
            return "couple"
        case _ where value == 3:
            return "few"
        case _ where value > 8:
            return "many"
        default:
            return "some"
        }
    }
    .sink { receivedValue in <3>
        print("The end result was \(receivedValue)")
    }
----
<1> Just is a publisher that creates an `<Int>`, `<Never>` type combination, provides a single value and then completes.
<2> the closure provided to the `.map()` function takes in an `<Int>` and transforms it into a `<String>`. Since the failure type of <Never> is not changed, it is passed through.
<3> `sink`, the subscriber, receives the `<String>`, `<Never>` combination.


[sidebar]
****
When you are creating pipelines in Xcode and don't match the types, the error message from Xcode may include a helpful _fixit_.
In some cases, such as the example above, the compiler is unable to infer the return types of closure provided to `map` withpout specifying the return type.
Xcode (11 beta 2 and beta 3) displays this as the error message: `Unable to infer complex closure return type; add explicit type to disambiguate`.
In the example above, we explicitly specified the type being returned with the line `value -> String in`.
****

You can view Combine publishers, operators, and subscribers as having two parallel types that both need to be aligned - one for the functional case and one for the error case.
Designing your pipeline is frequently choosing how to convert one or both of those types and the associated data with it.

More examples, and some common tasks, are detailed in the <<patterns.adoc#patterns,section on patterns>>.

// force a page break - ignored in HTML rendering
<<<

[#core-lifecycle]
== Lifecycle of Publishers and Subscribers

The data flow in Combine is driven by, and starts from, the subscriber.
This is how Combine supports the concept of back pressure.

Internally, Combine supports this with the enumeration https://developer.apple.com/documentation/combine/subscribers/demand[Demand].
When a subscriber is communicating with a publisher, it requests data based on demand.
This request is what drives calling all the closures up the composed pipeline.

Because subscribers drive the closure execution, it also allows Combine to support cancellation.
Cancellation can be triggered by the subscriber.

This is all enabled by subscribers and publishers communicating in a well defined sequence, or lifecycle.

. When the subscriber is attached to a publisher, it starts with a call to `.subscribe(Subscriber)`.
. The publisher in turn acknowledges the subscription calling `receive(subscription)`.

** After the subscription has been acknowledged, the subscriber requests _N_ values with `request(_ : Demand)`.
** The publisher may then (as it has values) sending _N_ (or fewer) values: `receive(_ : Input)`.
A publisher should never send **more** than the demand requested.
** Also after the subscription has been acknowledged, the subscriber can send a https://developer.apple.com/documentation/combine/subscribers/completion[cancellation] with `.cancel()`

. A publisher may optionally send https://developer.apple.com/documentation/combine/subscribers/completion[completion]: `receive(completion:)` which is also how errors are propogated.

[#core-publishers]
== Publishers

The publisher is the provider of data.
The https://developer.apple.com/documentation/combine/publisher[publisher protocol] has a strict contract returning values when asked from subscribers, and possibly terminating with an explicit completion enumeration.

<<reference.adoc#reference-just>> and <<reference.adoc#reference-future>> are extremely common sources to start your own publisher from a value or function.
Combine provides a number of additional convenience publishers:

//TODO(heckj) - convert to xref to reference sections on these operators
[cols="3*^"]
|===
| <<reference.adoc#reference-just>>
| <<reference.adoc#reference-future>>
| <<reference.adoc#reference-published>>

| <<reference.adoc#reference-once>>
| <<reference.adoc#reference-optional>>
| <<reference.adoc#reference-sequence>>

| <<reference.adoc#reference-empty>>
| <<reference.adoc#reference-fail>>
| <<reference.adoc#reference-deferred>>

|===

A number of Apple APIs outside of Combine provide publishers as well.
// TODO(heckj): come back and map these to xref's to the reference section when created

* SwiftUI provides https://developer.apple.com/documentation/swiftui/objectbinding[`@ObjectBinding`] which can be used to create a publisher.

* https://developer.apple.com/documentation/foundation/notificationcenter[`NoticationCenter`] https://developer.apple.com/documentation/foundation/notificationcenter/3329353-publisher[`.publisher`]

* https://developer.apple.com/documentation/foundation/timer[`Timer`] https://developer.apple.com/documentation/foundation/notificationcenter/3329353-publisher[`.publish`] and https://developer.apple.com/documentation/foundation/timer/timerpublisher[`Timer.TimerPublisher`]

* https://developer.apple.com/documentation/foundation/urlsession[`URLSession`] https://developer.apple.com/documentation/foundation/urlsession/3329707-datataskpublisher[`dataTaskPublisher`]

* https://developer.apple.com/documentation/realitykit[`RealityKit`] https://developer.apple.com/documentation/realitykit/scene[`.Scene`] https://developer.apple.com/documentation/realitykit/scene/3254685-publisher[`.publisher()`]

[#core-operators]
== Operators

Operators are a convenient name for a number of pre-built functions that are included under Publisher in Apple's reference documentation.
These functions are all meant to be composed into pipelines.
Many will accept  one of more closures from the developer to define the business logic of the operator, while maintaining the adherance to the publisher/subscriber lifecycle.

Some operators support bringing together outputs from different pipelines, or splitting to send to multiple subscribers.
Operators may also have constraints on the types they will operate on.
Operators can also help with error handling and retry logic, buffering and prefetch, controlling timing, and supporting debugging.

// NOTE(heckj): add xref link to reference section when written

[cols="3*^"]
|===
3+h| Mapping elements
| <<reference.adoc#reference-scan>>
| <<reference.adoc#reference-tryScan>>
| <<reference.adoc#reference-setFailureType>>

| <<reference.adoc#reference-map>>
| <<reference.adoc#reference-tryMap>>
| <<reference.adoc#reference-flatMap>>
|===

[cols="3*^"]
|===
3+h| Filtering elements
| <<reference.adoc#reference-compactMap>>
| <<reference.adoc#reference-tryCompactMap>>
| <<reference.adoc#reference-replaceEmpty>>

| <<reference.adoc#reference-filter>>
| <<reference.adoc#reference-tryFilter>>
| <<reference.adoc#reference-replaceError>>

| <<reference.adoc#reference-removeDuplicates>>
| <<reference.adoc#reference-tryRemoveDuplicates>>
|
|===


[cols="3*^"]
|===
3+h| Reducing elements
| <<reference.adoc#reference-collect>>
| <<reference.adoc#reference-collectByCount>>
| <<reference.adoc#reference-collectByTime>>

| <<reference.adoc#reference-reduce>>
| <<reference.adoc#reference-tryReduce>>
| <<reference.adoc#reference-ignoreOutput>>
|===

[cols="3*^"]
|===
3+h| Mathematic opertions on elements
| <<reference.adoc#reference-comparison>>
| <<reference.adoc#reference-tryComparison>>
| <<reference.adoc#reference-count>>
|===

[cols="3*^"]
|===
3+h| Applying matching criteria to elements
| <<reference.adoc#reference-allSatisfy>>
| <<reference.adoc#reference-tryAllSatisfy>>
| <<reference.adoc#reference-contains>>

| <<reference.adoc#reference-containsWhere>>
| <<reference.adoc#reference-tryContainsWhere>>
|
|===

[cols="3*^"]
|===
3+h| Applying sequence operations to elements
| <<reference.adoc#reference-firstWhere>>
| <<reference.adoc#reference-tryFirstWhere>>
| <<reference.adoc#reference-first>>

| <<reference.adoc#reference-lastWhere>>
| <<reference.adoc#reference-tryLastWhere>>
| <<reference.adoc#reference-last>>

| <<reference.adoc#reference-dropWhile>>
| <<reference.adoc#reference-tryDropWhile>>
| <<reference.adoc#reference-dropUntilOutput>>

| <<reference.adoc#reference-concatenate>>
| <<reference.adoc#reference-drop>>
| <<reference.adoc#reference-prefixUntilOutput>>

| <<reference.adoc#reference-prefixWhile>>
| <<reference.adoc#reference-tryPrefixWhile>>
| <<reference.adoc#reference-output>>
|===

[cols="3*^"]
|===
3+h| Combining elements from multiple publishers
| <<reference.adoc#reference-combineLatest>>
| <<reference.adoc#reference-tryCombineLatest>>
| <<reference.adoc#reference-merge>>

| <<reference.adoc#reference-zip>>
|
|
|===

[cols="3*^"]
|===
3+h| Handling errors
| <<reference.adoc#reference-assertNoFailure>>
| <<reference.adoc#reference-catch>>
| <<reference.adoc#reference-retry>>
|===

[cols="3*^"]
|===
3+h| Adapting publisher types
| <<reference.adoc#reference-switchToLatest>>
| <<reference.adoc#reference-eraseToAnyPublisher>>
|
|===

[cols="3*^"]
|===
3+h| Controlling timing
| <<reference.adoc#reference-debounce>>
| <<reference.adoc#reference-delay>>
| <<reference.adoc#reference-measureInterval>>

| <<reference.adoc#reference-throttle>>
| <<reference.adoc#reference-timeout>>
|
|===

[cols="3*^"]
|===
3+h| Encoding and decoding
| <<reference.adoc#reference-encode>>
| <<reference.adoc#reference-decode>>
|
|===

[cols="3*^"]
|===
3+h| Working with multiple subscribers
| <<reference.adoc#reference-multicast>>
|
|
|===

[cols="3*^"]
|===
3+h| Debugging
| <<reference.adoc#reference-breakpoint>>
| <<reference.adoc#reference-handleEvents>>
| <<reference.adoc#reference-print>>
|===

[#core-subjects]
== Subjects

Subjects are a special case of publisher that also adhere to the https://developer.apple.com/documentation/combine/subject[`subject`] protocol.
This protocol requires subjects to have a `.send()` method to allow the developer to send specific values to a subscriber (or pipeline).

Subjects can be used to "inject" values into a stream, by calling the subject's `.send()` method.
This is useful for integrating existing imperative code with Combine.

A subject can also broadcast values to multiple subscribers.
If multiple subscribers are connected to a subject, it will fanning out values to the multiple subscribers when `send()` is invoked.

There are two built-in subjects with Combine:

The first is <<reference.adoc#reference-currentValueSubject>>.

// TODO(heckj) collapse some of this over to the reference section

* CurrentValue remembers the current value so that when a subscriber is attached, it immediately receives the current value.

It is created and initialized with an initial value.
When a subscriber is connected to it and requests data, the initial value is sent.
Further calls to `.send()` afterwards will then send those values to any subscribers.

The second is <<reference.adoc#reference-passthroughSubject>>.

// TODO(heckj) collapse some of this over to the reference section

* Passthrough doesn't maintain any state - just passes through provided values.

When it is created, only the types are defined.
When a subscriber is connected and requests data, it will not receive any values until a `.send()` call is invoked.
Calls to `.send()` will then send values to any subscribers.

PassthroughSubject is extremely useful when writing tests for pipelines, as sending of any requested data (or a failure) is under the test writer's control using the `.send()` function.

Both CurrentValueSubject and PassthroughSubject are also useful for creating publishers from objects conforming to the https://developer.apple.com/documentation/swiftui/bindableobject[`BindableObject`] protocol within SwiftUI.

[#core-subscribers]
== Subscribers

While https://developer.apple.com/documentation/combine/subscriber[`subscriber`] is the protocol used to receive data throughout a pipeline, _the Subscriber_ typically refers to the end of a pipeline.

There are two subscribers built-in to Combine: assign and sink.

Subscribers can support cancellation, which terminates a subscription and shuts down all the stream processing prior to any Completion sent by the publisher.
Both `Assign` and `Sink` conform to the https://developer.apple.com/documentation/combine/cancellable[cancellable protocol].

https://developer.apple.com/documentation/combine/subscribers/assign[`assign`] applies values passed down from the publisher to an object defined by a keypath.
The keypath is set when the pipeline is created.
An example of this in swift might look like:

[source, swift]
----
.assign(to: \.isEnabled, on: signupButton)
----

https://developer.apple.com/documentation/combine/subscribers/sink[`sink`] accepts a closure that receives any resulting values from the publisher.
This allows the developer to terminate a pipeline with their own code.
This subscriber is also extremely helpful when writing unit tests to validate either publishers or pipelines.
An example of this in swift might look like:

[source, swift]
----
.sink { receivedValue in
    print("The end result was \(String(describing: receivedValue))")
}
----

Most other subscribers are part of other Apple frameworks.
For example, nearly every control in SwiftUI can act as a subscriber.
The https://developer.apple.com/documentation/swiftui/view/3278619-onreceive[`.onReceive(publisher)`] function is used on SwiftUI views to act as a subscriber, taking a closure akin to `.sink()` that can manipulate `@State` or `@Bindings` within SwiftUI.

An example of that in swift might look like:

[source, swift]
----
struct MyView : View {

    @State private var currentStatusValue = "ok"
    var body: some View {
        Text("Current status: \(currentStatusValue)")
    }
    .onReceive(MyPublisher.currentStatusPublisher) { newStatus in
        currentStatusValue = newStatus
    }
}
----

For any type of UI object (UIKit, AppKit, or SwiftUI), `.assign` can be used with pipelines to manipulate properties.

[#core-types]
== Swift types and exposing pipelines or subscribers

When you compose pipelines within swift, the chaining is interpretted as nesting generic types to the compiler.
If you expose a pipeline as a publisher, subscriber, or subject the exposed type can be exceptionally complex.

For example, if you created a publisher from a PassthroughSubject such as:

// Source for this at SwiftUI-NotesTests/CombinePatternTests.swift
[source, swift]
----
let x = PassthroughSubject<String, Never>()
    .flatMap { name in
        return Future<String, Error> { promise in
            promise(.success(""))
            }.catch { _ in
                Just("No user found")
            }.map { result in
                return "\(result) foo"
        }
}
----

The resulting type would reflect that composition:

[source, swift]
----
Publishers.FlatMap<Publishers.Map<Publishers.Catch<Future<String, Error>, Just<String>>, String>, PassthroughSubject<String, Never>>
----

When you want to expose the code, all of that composition detail can be very distracting and make your publisher, subject, or subscriber) harder to use.
To clean up that interface, and provide a nice API boundary, the three major protocols all support methods that do type erasure.
This cleans up the exposed type to a simpler generic form.

These three methods are:

* https://developer.apple.com/documentation/combine/publisher/3241548-erasetoanypublisher[`.eraseToAnyPublisher()`]
* https://developer.apple.com/documentation/combine/subscriber/3241649-erasetoanysubscriber[`.eraseToAnySubscriber()`]
* https://developer.apple.com/documentation/combine/subject/3241648-erasetoanysubject[`.eraseToAnySubject()`]

If you updated the above code to add .eraseToAnyPublisher() at the end of the pipeline:

[source, swift]
----
let x = PassthroughSubject<String, Never>()
    .flatMap { name in
        return Future<String, Error> { promise in
            promise(.success(""))
            }.catch { _ in
                Just("No user found")
            }.map { result in
                return "\(result) foo"
        }
}.eraseToAnyPublisher()
----

The resulting type would simplify to:

[source, swift]
----
AnyPublisher<String, Never>
----

[#core-threads]
== Pipelines and threads

Combine is not just a single threaded construct.
Combine allows for publishers to specify the scheduler used when either receiving from an upstream publisher (in the case of operators), or when sending to a downstream subscriber.
This is critical when working with a subscriber that updates UI elements, as that should always be called on the main thread.

You may see this in code as an operator, for example:

[source, swift]
----
    .receive(on: RunLoop.main)
----

// force a page break - ignored in HTML rendering
<<<
