[#developingwith]
= Developing with Combine

Developing with combine can take any of a number of different forms.

A common starting point is composing pipelines, leveraging existing publishers, operators, and subcribers.
A number of examples within this book highlight various patterns, many of which are aimed at providing declarative responses to user inputs within interfaces.

You may also want to create APIs that integrate more easily into combine.
For example, creating a publisher that encapsulates a remote API, returning a single result or a series of results.

Or you might be creating a subscriber to consume and process data over time.

== Reasoning about pipelines

When developing with combine, there are two broader patterns of how publishers are used that frequently recur: one-shot and continuous.

The first is what I'm calling a "one-shot" publisher or pipeline.
These publishers are expected to create a single response (or perhaps no response) and then terminate normally.

The second is what I'm calling a "continuous" publisher.
These publishers, or more often pipelines, are expected to be always active and providing the means to respond to ongoing events, either user initiated or another source.
In this case, the lifetime of the pipeline is significant longer, and it is often not desirable to have such pipelines fail or terminate.

When you are thinking about your development and how to use combine, it is often beneficial to think about pipelines as being one of these types, and mixing them together to achieve your goals.

For example, the pattern <<patterns.adoc#patterns-continual-error-handling>> in this book explicitly uses one-shot pipelines to support error handling on a continual pipeline.

When you are creating an instance of a publisher or a pipeline, it is worthwhile to be thinking about how you want it to work - to either be a one-shot, or continual.
This choice will often inform if you do with error handling or if you want to deal with operators that manipulate the timing of the events (such as <<reference.adoc#reference-debounce>> or <<reference.adoc#reference-throttle>>).

In addition to how much data the pipeline or publisher will provide, and the expectations that come from that, you will often want to think concretely about what type the pipeline provides.
Quite a number of pipelines are more about transforming data through various types, and handling possible error conditions in that processing.
A good example of this is the use of returning a pipeline returning a list in the pattern <<patterns.adoc#patterns-update-interface-userinput>> to provide a means to represent an "empty" result, even though the list is never expected to have more than 1 item within it.

Ultimately, using combine is grounded at both ends by the originating publisher, and how it is providing data (when it is available), and the subscriber ultimately consuming the data.

[#developingwith-types]
== Swift types and exposing pipelines or subscribers

When you compose pipelines within swift, the chaining of functions results in the type being exposed as nesting generic types.
If you are creating a pipeline, and then wanting to provide that as an API to another part of your code, the type definition for the exposed property or function can be exceptionally complex.

To illustrate the exposed type complexity, if you created a publisher from a PassthroughSubject such as:

// Source for this at SwiftUI-NotesTests/CombinePatternTests.swift
[source, swift]
----
let x = PassthroughSubject<String, Never>()
    .flatMap { name in
        return Future<String, Error> { promise in
            promise(.success(""))
            }.catch { _ in
                Just("No user found")
            }.map { result in
                return "\(result) foo"
        }
}
----

The resulting type is:

[source, swift]
----
Publishers.FlatMap<Publishers.Map<Publishers.Catch<Future<String, Error>, Just<String>>, String>, PassthroughSubject<String, Never>>
----

When you want to expose the code, all of that composition detail can be very distracting and make your code harder to use.

To clean up that interface, and provide a nice API boundary, there are type erased classes which can wrap either publishers or subscribers.
These explicitly hide the type complexity that builds up from chained functions in swift.

The two classes used to expose simplified types for subscribers and publishers are:

* https://developer.apple.com/documentation/combine/anysubscriber[AnySubscriber]
* https://developer.apple.com/documentation/combine/anypublisher[AnyPublisher]

Most publishers also include a convenience method `eraseToAnyPublisher` that returns an instance of AnyPublisher.
`eraseToAnyPublisher` is used very much like an operator, often as the last element in a chained pipeline, to simplify the type returned.

If you updated the above code to add .eraseToAnyPublisher() at the end of the pipeline:

[source, swift]
----
let x = PassthroughSubject<String, Never>()
    .flatMap { name in
        return Future<String, Error> { promise in
            promise(.success(""))
            }.catch { _ in
                Just("No user found")
            }.map { result in
                return "\(result) foo"
        }
}.eraseToAnyPublisher()
----

The resulting type would simplify to:

[source, swift]
----
AnyPublisher<String, Never>
----

This same technique can be immensely useful when constructing smaller pipelines within closures.
For example, when you want to return a publisher in the closure for a <<reference.adoc#reference-flatmap>> operator, you can have a much simpler time reasoning about types by explicitly asserting the closure should expect `AnyPublisher` with the relevant associated types.
An example of this can be seen in <<patterns.adoc#patterns-sequencing-operations>>.

[#developingwith-threads]
== Pipelines and threads

Combine is not just a single threaded construct.
Operators, as well as publishers, can run on different dispatch queues or runloops.
Composed pipelines can run across a single queue, or transfer across a number of queues or threads.

Combine allows for publishers to specify the scheduler used when either receiving from an upstream publisher (in the case of operators), or when sending to a downstream subscriber.
This is critical when working with a subscriber that updates UI elements, as that should always be called on the main thread.

You may see this in code as an operator, for example:

[source, swift]
----
.receive(on: RunLoop.main)
----

A number of operators can impact what thread or queue is being used to do the relevant processing.
<<reference.adoc#reference-receive>> and <<reference.adoc#reference-subscribe>> are the two most common, explicitly moving execution of operators after and prior to their invocation respectively.

A number of additional operators have parameters that include a scheduler.
Examples include <<reference.adoc#reference-delay>>, <<reference.adoc#reference-debounce>>, and <<reference.adoc#reference-throttle>>.
These also have an impact on the queue executing the work - both for themselves and then any operators following in a pipeline.
These operators all take a `scheduler` parameter, which switches to the relevant thread or queue to do the work.
Any operators following them will also be invoked on their scheduler, giving them an impact somewhat like <<reference.adoc#reference-receive>>.

If you want to be explicit about which thread context an operator or subsequent operation will run within, define it with the <<reference.adoc#reference-receive>> operator.

== developing to use combine

__YET TO BE DEVELOPED__

integrating APIs into combine:

* as publisher (returning a publisher)

* as a subscriber (accepting data to do something...)

declaratively pipelines

- decide what you want it to do
- map through the types needed, and error handling

To integrate an external API into a pipeline
- map & switchToLatest
- flatMap
- sequenced pipelines, linked with subjects (or @Published)

== how to create a subscriber/implementing your own subscriber

__YET TO BE DEVELOPED__

https://developer.apple.com/documentation/combine/subscriber[Subscriber]

types:
* Input
* Failure

required functions:
* receive(Self.Input) -> Subscribers.Demand
* receive(subscription: Subscription)
* receive(completion: Subscribers.Completion<Self.Failure>)

* receive() -> Subscribers.Demand (when input void)

== implementing your own publisher


__YET TO BE DEVELOPED__

// force a page break - ignored in HTML rendering
<<<
'''
