[#patterns-debugging-breakpoint]
== Debugging pipelines with the debugger

__Goal__::

* To gain understanding of why a pipeline isn't operating as you expect...

__References__::

* <<reference.adoc#reference-handleevents>>
* <<reference.adoc#reference-map>>

__See also__::

* <<#patterns-debugging-print>>
* <<#patterns-debugging-handleevents>>

__Code and explanation__::

You can easily set a breakpoint within any closure to any operator within a pipeline, triggering the debugger to activate to inspect the data.
Since the <<reference.adoc#reference-map>> operator is frequently used for simple output type conversions, it is often an excellent candidate that has a closure you can use.
If you want to see into the control messages, then a breakpoint within any of the closures provided to <<reference.adoc#reference-handleevents>> makes a very convenient target.


You can also use the <<reference.adoc#reference-breakpoint>> operator to trigger the debugger, which can be a very quick and convenient way to see what is happening in a pipeline.
The breakpoint operator acts very much like handleEvents, taking a number of optional parameters, closures that are expected to return a boolean, and if true will invoke the debugger.

The optional closures include:

* `receiveSubscription`
* `receiveOutput`
* `receiveCompletion`

.breakpoint(
    receiveSubscription: <#T##((Subscription) -> Bool)?##((Subscription) -> Bool)?##(Subscription) -> Bool#>, receiveOutput: <#T##((String?) -> Bool)?##((String?) -> Bool)?##(String?) -> Bool#>,
    receiveCompletion: <#T##((Subscribers.Completion<Never>) -> Bool)?##((Subscribers.Completion<Never>) -> Bool)?##(Subscribers.Completion<Never>) -> Bool#>)

This allows you to provide logic to evaluate the data being passed through, and only triggering a breakpoint when your specific conditions are met.
With very active pipelines processing a lot of data, this can be a great tool to be more surgical in getting the debugger active when you need it, and letting the other data move on by.

If you are only interested in the breaking into the debugger on error conditions, then convenience operator <<reference.adoc#reference-breakpointonerror>> is perfect.
It takes no parameters or closures, simply invoking the debugger when an error condition of any form is passed through the pipeline.

. breakPoint
  * if you want to break into a debugger, add in a closure that returns true and you can inspect to your heart's content
  ** closure's on `receiveSubscription`, `receiveOutput`, and `receiveCompletion`

  * might also be interesting to use breakpointOnError() which triggers only when a failure completion


// force a page break - in HTML rendering is just a <HR>
<<<
'''
