[#patterns-debugging]
== Debugging pipelines

__Goal__::

* For testing a subscriber (how it reacts):

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

. use print() and/or print("prefixValue") to get console output of what's happening in the pipeline lifecycle
  * create a .sink() to capture results, and drive it with a PassthroughSubject for specific control

. add a handleEvents() operator
  * create closures to do additional poking at values or digging into more structured pieces than get exposed with a print()
  * allows you to ignore some sections you don't care about
  * closures on `receiveSubscription`, `receiveRequest`, `receiveCancel`, `receiveOutput`, and `receiveCompletion`

. breakPoint
  * if you want to break into a debugger, add in a closure that returns true and you can inspect to your heart's content
  ** closure's on `receiveSubscription`, `receiveOutput`, and `receiveCompletion`

  * might also be interesting to use breakpointOnError() which triggers only when a failure completion


// force a page break - in HTML rendering is just a <HR>
<<<
'''
