[#patterns]
= Patterns and Recipes

Included are a series of patterns and examples of Publishers, Subscribers, and pipelines.
These examples are meant to illustrate how to use the Combine framework to accomplish various tasks.

[NOTE]
====
__Since this is a work in progress:__
if you have a suggestion for a pattern or recipe, I'm happy to consider it.

Please https://github.com/heckj/swiftui-notes/issues/new/choose[Open an issue] in GitHub to request something.
====

[#patterns-sink-subscriber]
== Pattern 1.1: Creating a subscriber with sink

__Goal__::

* To receive the output, and the errors or completion messages, generated from a publisher or through a pipeline, you can create a subscriber with `sink`.

__References__::

* <<reference.adoc#reference-sink>>

__See also__::

* <<#patterns-assign-subscriber>>
* <<#patterns-testing-publisher>>
* <<#patterns-testing-pipeline>>

__Code and explanation__::

Sink creates an all-purpose subscriber to capture or react the data from a Combine pipeline, while also supporting cancellation and the <<coreconcepts.adoc#core-lifecycle,publisher subscriber lifecycle>>.

.simple sink
[source, swift]
----
let cancellablePipeline = publishingSource.sink { someValue in <1>
    // do what you want with the resulting value passed down
    // be aware that depending on the data type being returned, you may get this closure invoked
    // multiple times.
    print(".sink() received \(someValue)")
})
----
<1> The simple version of a sink is very compact, with a single trailing closure that only receives data when presented through the pipeline.

.sink with completions and data
[source, swift]
----
let cancellablePipeline = publishingSource.sink(receiveCompletion: { completion in <1>
    switch completion {
    case .finished:
        // no associated data, but you can react to knowing the request has been completed
        break
    case .failure(let anError):
        // do what you want with the error details, presenting, logging, or hiding as appropriate
        print("received the error: ", anError)
        break
    }
}, receiveValue: { someValue in
    // do what you want with the resulting value passed down
    // be aware that depending on the data type being returned, you may get this closure invoked
    // multiple times.
    print(".sink() received \(someValue)")
})

cancellablePipeline.cancel() <2>
----

<1> Sinks are created by chaining the code from a publisher or pipeline, and terminate the pipeline.
When the sink is created or invoked on a publisher, it implicitly starts <<coreconcepts.adoc#core-lifecycle,the lifecycle>> with the `subscribe` and will request unlimited data.
<2> Creating a sink is cancellable subscriber, so at any time you can take the reference that terminated with sink and invoke `.cancel()` on it to invalidate and shut down the pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-assign-subscriber]
== Pattern 1.2: Creating a subscriber with assign

__Goal__::

* To use the results of a pipeline to set a value, often a property on a user interface view or control, but any KVO compliant object can be the target

__References__::

* <<reference.adoc#reference-assign>>
* <<reference.adoc#reference-receive>>

__See also__::

* <<#patterns-sink-subscriber>>

__Code and explanation__::

Assign is a subscriber that's specifically designed to apply data from a publisher or pipeline into a property, updating that property whenever it receives data.
Like sink, it activates when created and requests an unlimited data updates.
Assign requires the failure type to be specified as `<Never>`, so if your pipeline could fail (such as using an operator like tryMap) you will need to <<#patterns-general-error-handling,convert or handle the the failure cases>> before using `.assign`.

.simple sink
[source, swift]
----
let cancellablePipeline = publishingSource <1>
    .receive(on: RunLoop.main) <2>
    .assign(to: \.isEnabled, on: yourButton) <3>

cancellablePipeline.cancel() <4>
----

<1> `.assign` is typically chained onto a publisher when you create it, and the return value is cancellable.
<2> If `.assign` is being used to update a user interface element, you need to make sure that it is being updated on the main thread. This call makes sure the subscriber is received on the main thread.
<3> Assign references the property being updated using a https://developer.apple.com/documentation/swift/referencewritablekeypath[key path], and a reference to the object being updated.
<4> At any time you can can to terminate and invalidate pipelines with cancel(). Frequently, you cancel the pipelines when you deactivate the objects (such as a viewController) that are getting updated from the pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-datataskpublisher-decode]
== Pattern 2.1: Making a network request with dataTaskPublisher

__Goal__::

* One of the common use cases is requesting JSON data from a URL and decoding it.

__References__::

* <<reference.adoc#reference-datataskpublisher>>
* <<reference.adoc#reference-map>>
* <<reference.adoc#reference-decode>>
* <<reference.adoc#reference-sink>>
* <<reference.adoc#reference-subscribe>>

__See also__::

* <<#patterns-datataskpublisher-trymap>>
* <<#patterns-oneshot-error-handling>>
* <<#patterns-retry>>

__Code and explanation__::

This can be readily accomplished with Combine using
<<reference.adoc#reference-datataskpublisher>> followed by a series of operators that process the
data.
Minimally, this is <<reference.adoc#reference-map>> and <<reference.adoc#reference-decode>> before going into your subscriber.

https://developer.apple.com/documentation/foundation/urlsession/3329708-datataskpublisher[dataTaskPublisher] on https://developer.apple.com/documentation/foundation/urlsession[URLSession].

The simplest case of using this might be:

[source, swift]
----
let myURL = URL(string: "https://postman-echo.com/time/valid?timestamp=2016-10-10")
// checks the validity of a timestamp - this one returns {"valid":true}
// matching the data structure returned from https://postman-echo.com/time/valid
fileprivate struct PostmanEchoTimeStampCheckResponse: Decodable, Hashable { <1>
    let valid: Bool
}

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!) <2>
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .map { $0.data } <3>
    .decode(type: PostmanEchoTimeStampCheckResponse.self, decoder: JSONDecoder()) <4>

let cancellableSink = remoteDataPublisher.sink
    .sink(receiveCompletion: { completion in
            print(".sink() received the completion", String(describing: completion))
            switch completion {
                case .finished: <5>
                    break
                case .failure(let anError): <6>
                    print("received error: ", anError)
            }
    }, receiveValue: { someValue in <7>
        print(".sink() received \(someValue)")
    })
----

<1> Commonly you'll have a struct defined that supports at least https://developer.apple.com/documentation/swift/decodable[Decodable] (if not the full https://developer.apple.com/documentation/swift/codable[Codable protocol]). This struct can be defined to only pull the pieces you're interested in from the JSON provided over the network.
<2> dataTaskPublisher is instantiated from URLSession. You can configure your own options on URLSession, or use the general shared session as you require.
<3> The data that is returns down the pipeline is a tuple: `(data: Data, response: URLResponse)`. The <<reference.adoc#reference-map>> operator is used to get the data and drop the URL response, returning just Data down the pipeline.
<4> <<reference.adoc#reference-decode>> is used to load the data and attempt to transform it into the struct defined. Decode can throw an error itself if the decode fails. If it succeeds, the object passed down the pipeline will be the struct from the JSON data.
<5> If the decoding happened without errors, the finished completion will be triggered, and the value will also be passed to the receiveValue closure.
<6> If the a failure happened (either with the original network request or the decoding), the error will be passed into with the `.failure` completion.
<7> Only if the data succeeded with request and decoding will this closure get invoked, and the data format received with be an instance of the struct `PostmanEchoTimeStampCheckResponse`.

[#patterns-datataskpublisher-trymap]
== Pattern 2.2: Stricter request processing with dataTaskPublisher

__Goal__::

* When URLSession makes a connection, it only reports an error if the remote server doesn't respond. You may want to consider a number of responses, based on status code, to be errors. To accomplish this, you can use tryMap to inspect the http response and throw an error in the pipeline.

__References__::

* <<reference.adoc#reference-datataskpublisher>>
* <<reference.adoc#reference-trymap>>
* <<reference.adoc#reference-decode>>
* <<reference.adoc#reference-sink>>
* <<reference.adoc#reference-subscribe>>

__See also__::

* <<#patterns-datataskpublisher-decode>>
* <<#patterns-oneshot-error-handling>>
* <<#patterns-retry>>


__Code and explanation__::

To have more control over what is considered a failure in the URL response, use a `tryMap` operator on the tuple response from dataTaskPublisher.
Since dataTaskPublisher returns both the response data and the URLResponse into the pipeline, you can immediately inspect the response and throw an error of your own if desired.

An example of that might look like:

[source, swift]
----
let myURL = URL(string: "https://postman-echo.com/time/valid?timestamp=2016-10-10")
// checks the validity of a timestamp - this one returns {"valid":true}
// matching the data structure returned from https://postman-echo.com/time/valid
fileprivate struct PostmanEchoTimeStampCheckResponse: Decodable, Hashable {
    let valid: Bool
}
enum testFailureCondition: Error {
    case invalidServerResponse
}


let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    .tryMap { data, response -> Data in <1>
                guard let httpResponse = response as? HTTPURLResponse, <2>
                    httpResponse.statusCode == 200 else { <3>
                        throw testFailureCondition.invalidServerResponse <4>
                }
                return data <5>
    }
    .decode(type: PostmanEchoTimeStampCheckResponse.self, decoder: JSONDecoder())

let cancellableSink = remoteDataPublisher.sink
    .sink(receiveCompletion: { completion in
            print(".sink() received the completion", String(describing: completion))
            switch completion {
                case .finished:
                    break
                case .failure(let anError):
                    print("received error: ", anError)
            }
    }, receiveValue: { someValue in
        print(".sink() received \(someValue)")
    })
----

Where the <<#patterns-datataskpublisher-decode, previous pattern>> used a <<reference.adoc#reference-map>> operator, this uses tryMap, which allows us to identify and throw errors in the pipeline based on what was returned.

<1> <<reference.adoc#reference-trymap>> still gets the tuple of `(data: Data, response: URLResponse)`, and is defined here as returning just the type of Data down the pipeline.
<2> Within the closure for tryMap, we can cast the response to HTTPURLResponse and dig deeper into it, including looking at the specific status code.
<3> In this case, we want to consider **anything** other than a 200 response code as a failure. HTTPURLResponse.status_code is an Int type, so you could also have logic such as `httpResponse.statusCode > 300`.
<4> If the predicates aren't met, then we can throw an instance of an error of our choosing, `invalidServerResponse` in this case.
<5> If no error has occured, then we simply pass down Data for further processing.

When an error is triggered on the pipeline, a `.failure` completion is sent with the error encapsulated within it, regardless of where it happened in the pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-general-error-handling]
== Error Handling

The examples above expected that the subscriber would handle the error conditions, if they occured.
However, you are not always able to control the subscriber - as might be the case if you're using SwiftUI view properties as the subscriber, and you're providing the publisher.
In these cases, you need to build your pipeline so that the output types match the subscriber types.

For example, if you are working with SwiftUI and the you want to use `.assign` to set the `isEnabled` property on a button, the subscriber will have a few requirements:

. the subcriber should match the type output of `<Bool>`, `<Never>`
. the subscriber should be called on the main thread

With a publisher that can throw an error (such as `dataTaskPublisher`), you need to construct a pipeline to convert the output type, but also handle the error within the pipeline to match a failure type of `<Never>`.

How you handle the errors within a pipeline is very dependent on how the pipeline is working.
If the pipeline is set up to return a single result and terminate, continue to <<patterns-oneshot-error-handling>>.
If the pipeline is set up to continually update, the error handling needs to be a little more complex.
Jump ahead to <<patterns-continual-error-handling>>.

[#patterns-assertNoFailure]
=== Pattern 3.1: verifying a failure hasn't happened using assertNoFailure

__Goal__::

* Verify no error has occured within a pipeline

__References__::

* <<reference.adoc#reference-assertnofailure>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

Useful in testing invariants in pipelines, the assertNoFailure operator also converts the failure type to `<Never>`.
The operator will cause the application to terminate (and tests to crash to a debugger) if the assertion is triggered.

This is useful for verifying the invariant of having dealt with an error.
If you are sure you handled the errors and need to map a pipeline which technically can generate a failure type of `<Error>` to a subscriber that requires a failure type of `<Never>`.

It is far more likely that you want to handle the error with and not have the application terminate.
Look forward to <<#patterns-oneshot-error-handling>> and <<#patterns-continual-error-handling>> for patterns of how to provide logic to handle errors in a pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-oneshot-error-handling]
=== Pattern 3.2: Using catch to handle errors in a one-shot pipeline

__Goal__::

* If you need to handle a failure within a pipeline, for example before using the `assign` operator or another operator that requires the failure type to be `<Never>`, you can use `catch` to provide the appropriate logic.

__References__::

* <<reference.adoc#reference-catch>>
* <<reference.adoc#reference-just>>

__See also__::

* <<#patterns-retry>>
* <<#patterns-continual-error-handling>>
* <<#patterns-constrained-network>>

__Code and explanation__::

`catch` handles errors by replacing the upstream publisher with another publisher that you provide as a return in a closure.

[WARNING]
====
Be aware that this effectively terminates the earlier portion of the pipeline.
If you're using a one-shot publisher (one that doesn't create more than a single event), then this is fine.
====

For example, `dataTaskPublisher` is a one-shot publisher and you might use catch with it to ensure that you get a response, returning a placeholder in the event of an error.
Extending our previous example to provide a default response:

[source, swift]
----
struct IPInfo: Codable {
    // matching the data structure returned from ip.jsontest.com
    var ip: String
}
let myURL = URL(string: "http://ip.jsontest.com")
// NOTE(heckj): you'll need to enable insecure downloads in your Info.plist for this example
// since the URL scheme is 'http'

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .map({ (inputTuple) -> Data in
        return inputTuple.data
    })
    .decode(type: IPInfo.self, decoder: JSONDecoder()) <1>
    .catch { err in <2>
        return Publishers.Just(IPInfo(ip: "8.8.8.8"))<3>
    }
    .eraseToAnyPublisher()
----

<1> Often, a catch operator will be placed after several operators that could fail, in order to provide a fallback or placeholder in the event that any of the possible previous operations failed.
<2> When using catch, you get the error type in and can inspect it to chosoe how you provide a response.
<3> The Just publisher is frequently used to either start another one-shot pipeline or to directly provide a placeholder response in the event of failure.

A possible problem with this technique is that the if the original publisher generates more values to which you wish to react, the original pipeline has been ended.
If you are creating a pipeline that reacts to a `@Published` property, then after any failed value that activates the catch operator, the pipeline will cease to react further.
See <<reference.adoc#reference-catch>> for more illustration and examples of how this works.

If you want to continue to respond to errors and handle them, see <<#patterns-continual-error-handling>> for an example of how to do that using `flatMap`

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-retry]
=== Pattern 3.3: Retrying in the event of a temporary failure

__Goal__::

* The `retry` operator can be included in a pipeline to retry a subscription when a `.failure` completion occurs.

__References__::

* <<reference.adoc#reference-catch>>
* <<reference.adoc#reference-retry>>

__See also__::

* <<#patterns-oneshot-error-handling>>
* <<#patterns-continual-error-handling>>

__Code and explanation__::

When you specify this operator in a pipeline and it receives a subscription, it first tries to request a subscription from it's upstream publisher.
If the response to that subscription fails, then it will retry the subscription to the same publisher.

The retry operator can be specified with a number of retries to attempt.
If no number of retries is specified, it will attempt to retry indefinitely until it receives a .finished completion from it's subscriber.
If the number of retries is specified and all requests fail, then the `.failure` completion is passed down to the subscriber of this operator.

In practice, this is mostly commonly desired when attempting to request network resources with an unstable connection.
If you use a retry operator, you should add a specific number of retries so that the subscription doesn't effectively get into an infinite loop.

An example of the above example using retry in combination with a delay:

[source, swift]
----
let remoteDataPublisher = urlSession.dataTaskPublisher(for: self.mockURL!)
    .delay(for: DispatchQueue.SchedulerTimeType.Stride(integerLiteral: Int.random(in: 1..<5)), scheduler: backgroundQueue) <1>
    .retry(3) <2>
    .tryMap { data, response -> Data in <3>
        guard let httpResponse = response as? HTTPURLResponse,
            httpResponse.statusCode == 200 else {
                throw testFailureCondition.invalidServerResponse
        }
        return data
    }
    .decode(type: PostmanEchoTimeStampCheckResponse.self, decoder: JSONDecoder())
    .subscribe(on: backgroundQueue)
    .eraseToAnyPublisher()
----

<1> the delay operator will delay further processing on the pipeline, in this case for a random selection of 1 to 5 seconds. By adding delay here in the pipeline, it will always occur, even if the original request is successful.
<2> retry is specified as trying 3 times. If you specify retry without any options, it will retry infinitely, and may cause your pipeline to never resolve any values or completions.
<3> tryMap is being used to investigate errors after the retry so that retry will only re-attempt the request when the site didn't respond.

[WARNING]
====
When using the `retry()` operator with `dataTaskPublisher`, verify that the URL you are requesting isn't going to have negative side effects if requested repeatedly or with a retry.
Ideally such requests are be expected to be idempotent.
====

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-continual-error-handling]
=== Pattern 3.4: Using flatMap with catch to handle errors

__Goal__::

* The `flatMap` operator can be used with `catch` to continue to handle errors on new published values.

__References__::

* <<reference.adoc#reference-flatmap>>
* <<reference.adoc#reference-just>>
* <<reference.adoc#reference-once>>
* <<reference.adoc#reference-catch>>

__See also__::

* <<#patterns-oneshot-error-handling>>
* <<#patterns-retry>>

__Code and explanation__::

The `flatMap` operator is the operator to use in handling errors on a continual flow of events.

You provide a closure to flatMap that can read in the value that was provided, and creates a one-shot closure that does the possibly failing work.
An example of this is requesting data from a network and then decoding the returned data.
You can include a <<reference.adoc#reference-catch>> operator to capture any errors and provide any appropriate value.

This is a perfect mechanism for when you want to maintain updates up an upstream publisher, as it creates one-shot publisher or short pipelines that send a single value and then complete for every incoming value.
The completion from the created one-shot publishers terminates in the flatMap and isn't passed to downstream subscribers.

An example of this with a dataTaskPublisher:

[source, swift]
----
let remoteDataPublisher = Just(self.testURL!) <1>
    .flatMap { url in <2>
        URLSession.shared.dataTaskPublisher(for: url) <3>
        .tryMap { data, response -> Data in <4>
            guard let httpResponse = response as? HTTPURLResponse,
                httpResponse.statusCode == 200 else {
                    throw testFailureCondition.invalidServerResponse
            }
            return data
        }
        .decode(type: PostmanEchoTimeStampCheckResponse.self, decoder: JSONDecoder()) <5>
        .catch {_ in <6>
            return Just(PostmanEchoTimeStampCheckResponse(valid: false))
        }
    }
    .subscribe(on: self.myBackgroundQueue!)
    .eraseToAnyPublisher()
----

<1> Just starts this publisher as an example by passing in a URL.
<2> flatMap takes the URL as input and the closure goes on to create a one-shot publisher chain.
<3> dataTaskPublisher uses the input url
<4> which flows to tryMap to parse for additional errors
<5> and finally decode to attempt to refine the returned data into a local type
<6> if any of these have failed, catch will convert the error into a placeholder sample, in this case an object with a preset `valid = false` property.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-constrained-network]
== Pattern 4: Requesting data from an alternate URL when the network is constrained

__Goal__::

* From Apple's WWDC 19 presentation https://developer.apple.com/videos/play/wwdc2019/712/[Advances in Networking, Part 1], a sample pattern was provided using `tryCatch` and `tryMap` operators to react to the specific error of having the network be constrained.

__References__::

* <<reference.adoc#reference-datataskpublisher>>
* <<reference.adoc#reference-trycatch>>
* <<reference.adoc#reference-trymap>>

__See also__::

* <<#patterns-oneshot-error-handling>>
* <<#patterns-retry>>

__Code and explanation__::

[NOTE]
====
This sample is originally from the WWDC session.
The API and example is evolving with the beta releases of Combine since that presentation.
`tryCatch` was missing in the beta2 release, and has returned in beta3.
====

[source, swift]
----
// Generalized Publisher for Adaptive URL Loading
func adaptiveLoader(regularURL: URL, lowDataURL: URL) -> AnyPublisher<Data, Error> {
    var request = URLRequest(url: regularURL) <1>
    request.allowsConstrainedNetworkAccess = false <2>
    return URLSession.shared.dataTaskPublisher(for: request) <3>
        .tryCatch { error -> URLSession.DataTaskPublisher in <4>
            guard error.networkUnavailableReason == .constrained else {
               throw error
            }
            return URLSession.shared.dataTaskPublisher(for: lowDataURL) <5>
        .tryMap { data, response -> Data in
            guard let httpResponse = response as? HTTPUrlResponse, <6>
                   httpResponse.status_code == 200 else {
                       throw MyNetworkingError.invalidServerResponse
            }
            return data
}
.eraseToAnyPublisher() <7>
----

This example, from Apple's WWDC, provides a function that takes two URLs - a primary and a fallback.
It returns a publisher that will request data and fall back requesting a secondary URL when the network is constrained.

<1> The request starts with an attempt requesting data.
<2> Setting `request.allowsConstrainedNetworkAccess` will cause the dataTaskPublisher to error if the network is constrained.
<3> Invoke the dataTaskPublisher to make the request.
<4> tryCatch is used to capture the immediate error condition and check for a specific error (the constrained network).
<5> If it finds an error, it creates a new one-shot publisher with the fall-back URL.
<6> The resulting publisher can still fail, and tryMap can map this a failure by throwing an error on HTTP response codes that map to error conditions
<7> eraseToAnyPublisher will do type erasure on the chain of operators so the resulting signature of the adaptiveLoader function is of type `AnyPublisher<Data, Error>`

In the sample, if the error returned from the original request wasn't an issue of the network being constrained, it passes on the .failure completion down the pipeline.
If the error is that the network is constrained, then the tryCatch operator creates a new request to an alternate URL.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-update-interface-userinput]
== Pattern 5.1: Declarative UI updates from user input

__Goal__::

* Querying a web based API and returning the data to be displayed in your UI

__References__::

* The Xcode project ViewController with this code is in the github project at https://github.com/heckj/swiftui-notes/blob/master/UIKit-Combine/ViewController.swift[`UIKit-Combine/ViewController.swift`]

* Publishers:
<<reference.adoc#reference-published>>,
<<reference.adoc#reference-datataskpublisher>>,
* Operators:
<<reference.adoc#reference-map>>,
<<reference.adoc#reference-switchtolatest>>,
<<reference.adoc#reference-receive>>,
<<reference.adoc#reference-throttle>>,
<<reference.adoc#reference-removeduplicates>>
* Subscribers:
<<reference.adoc#reference-assign>>

__See also__::

* <<#patterns-continual-error-handling>>
* <<#patterns-oneshot-error-handling>>
* <<#patterns-datataskpublisher-trymap>>

__Code and explanation__::

One of the primary benefits of a framework like Combine is setting up a declarative structure that defines how an interface will update to user input.

A pattern for integrating UIKit is setting up a variable which will hold a reference to the updated state, and then linking that with existing UIKit or AppKit controls within IBAction.

The sample here is a portion of the code at in a larger ViewController implementation.

This example overlaps with the next pattern <<#patterns-cascading-update-interface>>, which builds upon the initial publisher.

.https://github.com/heckj/swiftui-notes/blob/master/UIKit-Combine/GithubAPI.swift[UIKit-Combine/GithubAPI.swift]
[source, swift]
----
import UIKit
import Combine

class ViewController: UIViewController {

    @IBOutlet weak var github_id_entry: UITextField! <1>

    var usernameSubscriber: AnyCancellable?

    // username from the github_id_entry field, updated via IBAction
    @Published var username: String = "" <2>

    // github user retrieved from the API publisher. As it's updated, it
    // is "wired" to update UI elements
    @Published private var githubUserData: [GithubAPIUser] = []

    // MARK - Actions

    @IBAction func githubIdChanged(_ sender: UITextField) {
        username = sender.text ?? "" <3>
        print("Set username to ", username)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.

        usernameSubscriber = $username <4>
            .throttle(for: 0.5, scheduler: myBackgroundQueue, latest: true) <5>
            // ^^ scheduler myBackGroundQueue publishes resulting elements
            // into that queue, resulting on this processing moving off the
            // main runloop.
            .removeDuplicates() <6>
            .print("username pipeline: ") // debugging output for pipeline
            .map { username -> AnyPublisher<[GithubAPIUser], Never> in <7>
                return GithubAPI.retrieveGithubUser(username: username)
            }
            // ^^ type returned in the pipeline is a Publisher, so we use
            // switchToLatest to flatten the values out of that
            // pipline to return down the chain, rather than returning a
            // publisher down the pipeline.
            .switchToLatest() <8>
            // using a sink to get the results from the API search lets us
            // get not only the user, but also any errors attempting to get it.
            .receive(on: RunLoop.main)
            .assign(to: \.githubUserData, on: self) <9>
----

<1> The UITextField is the interface element which is driving the updates from user interaction.
<2> We defined a <<reference.adoc#reference-published> property to both hold the updates.
Because its a Published property, it provides a publisher reference that we can use to attach additional combine pipelines to update other variables or elements of the interface.
<3> We set the variable `username` from within an IBAction, which in turn triggers a data flow if the publisher `$username` has any subscribers.
<4> We in turn set up a subscriber on the publisher `$username` that does further actions. In this case the overall flow retrives an instance of a GithubAPIUser from Github's REST API.
<5> The <<reference.adoc#reference-throttle>> is there to keep from triggering a network request on ever request.
The throttle keeps it to a maximum of 1 request every half-second.
<6> <<reference.adoc#reference-removeduplicates>> is there to collapse events from the changing username so that API requests aren't made on rapidly changing values.
The removeDuplicates prevents redundant requests from being made, should the user edit and the return the previous value.
<7> map is used similiarly to flatMap in error handling here, returning an instance of a publisher.
The API object returns a publisher, which this map is invoking.
This doesn't return the value from the call, but the calling publisher itself.
<8> <<reference.adoc#reference-switchtolatest>> operator takes the instance of the publisher that is the element passed down the pipeline, and pulls out the data to push the elements further down the pipeline.
switchToLatest resolves that publisher into a value and passes that value down the pipeline, in this case an instance of `[GithubAPIUser]`.
<9> And assign at the end up the pipeline is the subscriber, which assigns the value into another variable

Continue on to <<#patterns-cascading-update-interface>> to expand this into multiple cascading updates of various UI elements.

[#patterns-cascading-update-interface]
== Pattern 5.2: Update the multiple pieces of your interface from a publisher update

__Goal__::

* Have multiple UI elements update triggered by an upstream subscriber

__References__::

* The ViewController with this code is in the github project at https://github.com/heckj/swiftui-notes/blob/master/UIKit-Combine/ViewController.swift[UIKit-Combine/ViewController.swift]
* The GithubAPI is in the github project at https://github.com/heckj/swiftui-notes/blob/master/UIKit-Combine/GithubAPI.swift[UIKit-Combine/GithubAPI.swift]

* Publishers:
<<reference.adoc#reference-published>>,
<<reference.adoc#reference-datataskpublisher>>,
<<reference.adoc#reference-just>>,
<<reference.adoc#reference-empty>>
* Operators:
<<reference.adoc#reference-decode>>,
<<reference.adoc#reference-catch>>,
<<reference.adoc#reference-map>>,
<<reference.adoc#reference-trymap>>,
<<reference.adoc#reference-switchtolatest>>,
<<reference.adoc#reference-filter>>,
<<reference.adoc#reference-handleevents>>,
<<reference.adoc#reference-subscribe>>,
<<reference.adoc#reference-receive>>,
<<reference.adoc#reference-throttle>>,
<<reference.adoc#reference-removeduplicates>>
* Subscribers:
<<reference.adoc#reference-sink>>,
<<reference.adoc#reference-assign>>

__See also__::

* <<#patterns-continual-error-handling>>
* <<#patterns-oneshot-error-handling>>
* <<#patterns-datataskpublisher-trymap>>

__Code and explanation__::

The example provided expands on a publisher updating from <<#patterns-update-interface-userinput>>, adding additional combine pipelines to update multiple UI elements.

The general pattern of this view starts with a textfield that accepts user input:

1. We using an IBAction to update the <<reference.adoc#reference-published>> username variable.
2. We have a subscriber (`usernameSubscriber`) attached `$username` publisher reference, which attempts to retrieve the GitHub user from the API.
The resulting variable `githubUserData` (also <<reference.adoc#reference-published>>) is a list of GitHub user objects.
Even though we only expect a single value here, we use a list because we can conveniently return an empty list on failure scenarios: unable to access the API or the username isn't registered at GitHub.
3. We have a "secondary" subscriber `apiNetworkActivitySubscriber` which another publisher from the GithubAPI object that provides values when the GithubAPI object starts or finishes making network requests.
4. We have a another subscriber `repositoryCountSubscriber` attached to `$githubUserData` that pulls the repository count off the github user data object and assigns it as the count to be displayed.
5. We have a final subscriber `avatarViewSubscriber` attached to `$githubUserData` that attempts to retrieve the image associated with the user's avatar for display.

The empty list is useful to return because when a username is provided that doesn't resolve, we want to explicitly remove any avatar image that was previously displayed.
To do this, we need the pipelines to fully resolve to some value, so that further pipelines are triggered and the relevant UI interfaces updated.

The subscribers (created with <<reference.adoc#reference-assign>> and <<reference.adoc#reference-sink>>) are stored as AnyCancellable variables on the ViewController instance.
Because they are defined on the class instance, the swift compiler creates initializers and deinitializers, which will cancel and clean up the publishers when the class is torn down.

[NOTE]
====
I *think* the above statement is true related to memory management and cancelling the pipelines, but I have not confirmed it.
Additionally, a lot of folks comfortable with RxSwift operators are using a "CancelBag" object to collect cancellable references, and cancel the pipelines on tear down.
An example of this can be seen at https://github.com/tailec/CombineExamples/blob/master/CombineExamples/Shared/CancellableBag.swift
====

The pipelines have been explicitly configured to work on a background queue using the <<reference.adoc#reference-subscribe>> operator.
Without that additional configured, the pipelines would be invoked and run on the main runloop since they were invoked from the UI, which causes a noticable slow-down in responsiveness in the simulator.
Likewise when the resulting pipelines assign or update UI elements, the <<reference.adoc#reference-receive>> operator is used to transfer that work back onto the main runloop.

[WARNING]
====
If you want to have the UI continuously updated from changes propogating through <<reference.adoc#reference-published>> properties, make sure that any configured pipelines have a <Never> failure type.
This is required for the <<reference.adoc#reference-assign>> operator.
But more importantly, it's a source of bugs when using a <<reference.adoc#reference-sink>> operator.
If the pipeline from a <<reference.adoc#reference-published>> variable terminates in a <<reference.adoc#reference-sink>> that accepts an Error failure type, the sink will send a termination signal if an error occures, which stops the pipeline from further processing even when the variable is updated.
====

.https://github.com/heckj/swiftui-notes/blob/master/UIKit-Combine/GithubAPI.swift[UIKit-Combine/GithubAPI.swift]
[source, swift]
----
import Founation
import Combine

enum APIFailureCondition: Error {
    case invalidServerResponse
}

struct GithubAPIUser: Decodable { <1>
    // A very *small* subset of the content available about
    //  a github API user for example:
    // https://api.github.com/users/heckj
    let login: String
    let public_repos: Int
    let avatar_url: String
}

struct GithubAPI { <2>
    // NOTE(heckj): I've also seen this kind of API access
    // object set up with with a class and static methods on the class.
    // I don't know that there's a specific benefit to make this a value
    // type/struct with a function on it.

    /// externally accessible publsher that indicates that network activity is happening in the API proxy
    static let networkActivityPublisher = PassthroughSubject<Bool, Never>() <3>

    /// creates a one-shot publisher that provides a GithubAPI User
    /// object as the end result. This method was specifically designed to
    /// return a list of 1 object, as opposed to the object itself to make
    /// it easier to distinguish a "no user" result (empty list)
    /// representation that could be dealt with more easily in a Combine
    /// pipeline than an optional value. The expected return types is a
    /// Publisher that returns either an empty list, or a list of one
    /// GithubAPUser, and with a failure return type of Never, so it's
    /// suitable for recurring pipeline updates working with a @Published
    /// data source.
    /// - Parameter username: username to be retrieved from the Github API
    static func retrieveGithubUser(username: String) -> AnyPublisher<[GithubAPIUser], Never> { <4>

        if username.count < 3 { <5>
            return Just([]).eraseToAnyPublisher()
            // return Publishers.Empty<GithubAPIUser, Never>()
            //    .eraseToAnyPublisher()
        }
        let assembledURL = String("https://api.github.com/users/\(username)")
        let publisher = URLSession.shared.dataTaskPublisher(for: URL(string: assembledURL)!)
            .handleEvents(receiveSubscription: { _ in <6>
                networkActivityPublisher.send(true)
            }, receiveCompletion: { _ in
                networkActivityPublisher.send(false)
            }, receiveCancel: {
                networkActivityPublisher.send(false)
            })
            .tryMap { data, response -> Data in <7>
                guard let httpResponse = response as? HTTPURLResponse,
                    httpResponse.statusCode == 200 else {
                        throw APIFailureCondition.invalidServerResponse
                }
                return data
        }
        .decode(type: GithubAPIUser.self, decoder: JSONDecoder()) <8>
        .map {
                [$0] <9>
        }
        .catch { err in <10>
            // return Publishers.Empty<GithubAPIUser, Never>()
            // ^^ when I originally wrote this method, I was returning
            // a GithubAPIUser? optional, and then a GithubAPIUser without
            // optional. I ended up converting this to return an empty
            // list as the "error output replacement" so that I could
            // represent that the current value requested didn't *have* a
            // correct github API response. When I was returing a single
            // specific type, using Publishers.Empty was a good way to do a
            // "no data on failure" error capture scenario.
            return Just([])
        }
        .eraseToAnyPublisher() <11>
        return publisher
    }
}
----

<1> The decodable struct created here is a subset of what's returned from the GitHub API.
Any pieces not defined in the struct are simply ignored when processed by the <<reference.adoc#reference-decode>> operator.
<2> The code to interact with the GitHub API was broken out into its own object, which I would normally have in a separate file.
The functions on the API struct return publishers, and are then mixed and merged with other pipelines in the ViewController.
<3> This struct also exposes a publisher using <<reference.adoc#reference-passthroughsubject>> that have set up to trigger Boolean values when it is actively making network requests.
<4> I first created the pipelines to return an optional GithubAPIUser instance, but found that there wasn't a convenient way to propogate "nil" or empty objects on failure conditions.
The code was then recreated to return a list, even though only a single instance was ever expected, to conveniently represent an "empty" object.
This was important for the use case of wanting to erase existing values in following pipelines reacting to the GithubAPIUser object "disappearing" - removing the repository count and avatar images in this case.
<5> The logic here is simply to prevent extraneous network requests, returning an empty result if the username being requested has less than 3 characters.
The commented out code is a bit of legacy from when I wanted to return nothing instead of an empty list.
<6> the <<reference.adoc#reference-handleevents>> operator here is how we are triggering updates for the network activity publisher.
We define closures that trigger on subscription and finalization (both completion and cancel) that invoke `send()` on the <<reference.adoc#reference-passthroughsubject>>.
This is an example of how we can provide metadata about a pipeline's operation as a separate publisher.
<7> <<reference.adoc#reference-trymap>> adds additional checking on the API response from github to convert correct responses from the API that aren't valid User instances into a pipeline failure condition.
<8> <<reference.adoc#reference-decode>> takes the Data from the response and decodes it into a single instance of `GithubAPIUser`
<9> <<reference.adoc#reference-map>> is used to take the single instance and convert it into a list of 1 item, changing the type to a list of `GithubAPIUser`: `[GithubAPIUser]`.
<10> <<reference.adoc#reference-catch>> operator captures the error conditions within this pipeline, and returns an empty list on failure while also converting the failure type to `Never`.
<11> <<reference.adoc#reference-erasetoanypublisher>> collapses the complex types of all the chained operators and exposes the whole pipeline as an instance of `AnyPublisher`.

.https://github.com/heckj/swiftui-notes/blob/master/UIKit-Combine/ViewController.swift[UIKit-Combine/ViewController.swift]
[source, swift]
----

import UIKit
import Combine

class ViewController: UIViewController {

    @IBOutlet weak var github_id_entry: UITextField!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet weak var repositoryCountLabel: UILabel!
    @IBOutlet weak var githubAvatarImageView: UIImageView!

    var repositoryCountSubscriber: AnyCancellable?
    var avatarViewSubscriber: AnyCancellable?
    var usernameSubscriber: AnyCancellable?
    var headingSubscriber: AnyCancellable?
    var apiNetworkActivitySubscriber: AnyCancellable?

    // username from the github_id_entry field, updated via IBAction
    @Published var username: String = ""

    // github user retrieved from the API publisher. As it's updated, it
    // is "wired" to update UI elements
    @Published private var githubUserData: [GithubAPIUser] = []

    // publisher reference for this is $username, of type <String, Never>
    var myBackgroundQueue: DispatchQueue = DispatchQueue(label: "viewControllerBackgroundQueue")
    let coreLocationProxy = LocationHeadingProxy()

    // MARK - Actions

    @IBAction func githubIdChanged(_ sender: UITextField) {
        username = sender.text ?? ""
        print("Set username to ", username)
    }

    // MARK - lifecycle methods

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.

        let apiActivitySub = GithubAPI.networkActivityPublisher <1>
        .receive(on: RunLoop.main)
            .sink { doingSomethingNow in
                if (doingSomethingNow) {
                    self.activityIndicator.startAnimating()
                } else {
                    self.activityIndicator.stopAnimating()
                }
        }
        apiNetworkActivitySubscriber = AnyCancellable(apiActivitySub)

        usernameSubscriber = $username <2>
            .throttle(for: 0.5, scheduler: myBackgroundQueue, latest: true)
            // ^^ scheduler myBackGroundQueue publishes resulting elements
            // into that queue, resulting on this processing moving off the
            // main runloop.
            .removeDuplicates()
            .print("username pipeline: ") // debugging output for pipeline
            .map { username -> AnyPublisher<[GithubAPIUser], Never> in
                return GithubAPI.retrieveGithubUser(username: username)
            }
            // ^^ type returned in the pipeline is a Publisher, so we use
            // switchToLatest to flatten the values out of that
            // pipline to return down the chain, rather than returning a
            // publisher down the pipeline.
            .switchToLatest()
            // using a sink to get the results from the API search lets us
            // get not only the user, but also any errors attempting to get it.
            .receive(on: RunLoop.main)
            .assign(to: \.githubUserData, on: self)

        // using .assign() on the other hand (which returns an
        // AnyCancellable) *DOES* require a Failure type of <Never>
        repositoryCountSubscriber = $githubUserData <3>
            .print("github user data: ")
            .map { userData -> String in
                if let firstUser = userData.first {
                    return String(firstUser.public_repos)
                }
                return "unknown"
            }
            .receive(on: RunLoop.main)
            .assign(to: \.text, on: repositoryCountLabel)

        let avatarViewSub = $githubUserData <4>
            // When I first wrote this publisher pipeline, the type I was
            // aiming for was <GithubAPIUser?, Never>, where the value was an
            // optional. The commented out .filter below was to prevent a `nil` // GithubAPIUser object from propogating further and attempting to
            // invoke the dataTaskPublisher which retrieves the avatar image.
            //
            // When I updated the type to be non-optional (<GithubAPIUser?,
            // Never>) the filter expression was no longer needed, but possibly
            // interesting.
            // .filter({ possibleUser -> Bool in
            //     possibleUser != nil
            // })
            // .print("avatar image for user") // debugging output
            .map { userData -> AnyPublisher<UIImage, Never> in
                guard let firstUser = userData.first else {
                    // my placeholder data being returned below is an empty
                    // UIImage() instance, which simply clears the display.
                    // Your use case may be better served with an explicit
                    // placeholder image in the event of this error condition.
                    return Just(UIImage()).eraseToAnyPublisher()
                }
                return URLSession.shared.dataTaskPublisher(for: URL(string: firstUser.avatar_url)!)
                    // ^^ this hands back (Data, response) objects
                    .handleEvents(receiveSubscription: { _ in
                        DispatchQueue.main.async {
                            self.activityIndicator.startAnimating()
                        }
                    }, receiveCompletion: { _ in
                        DispatchQueue.main.async {
                            self.activityIndicator.stopAnimating()
                        }
                    }, receiveCancel: {
                        DispatchQueue.main.async {
                            self.activityIndicator.stopAnimating()
                        }
                    })
                    .map { $0.data }
                    // ^^ pare down to just the Data object
                    .map { UIImage(data: $0)!}
                    // ^^ convert Data into a UIImage with its initializer
                    .subscribe(on: self.myBackgroundQueue)
                    // ^^ do this work on a background Queue so we don't screw
                    // with the UI responsiveness
                    .catch { err in
                        return Just(UIImage())
                    }
                    // ^^ deal the failure scenario and return my "replacement"
                    // image for when an avatar image either isn't available or
                    // fails somewhere in the pipeline here.
                    .eraseToAnyPublisher()
                    // ^^ match the return type here to the return type defined
                    // in the .map() wrapping this because otherwise the return
                    // type would be terribly complex nested set of generics.
            }
            .switchToLatest()
            // ^^ Take the returned publisher that's been passed down the chain
            // and "subscribe it out" to the value within in, and then pass
            // that further down.
            .subscribe(on: myBackgroundQueue)
            // ^^ do the above processing as well on a background Queue rather
            // than potentially impacting the UI responsiveness
            .receive(on: RunLoop.main)
            // ^^ and then switch to receive and process the data on the main
            // queue since we're messin with the UI

            // .assign(to: \.image, on: self.githubAvatarImageView)
            // this ^^^ line is returning a compiler error: Type of expression
            // is ambiguous without more context. I *thought* it would work,
            // but it's having an issue with the keyPath that I'm trying to
            // assign for the githubAvatarImageView.image.

            // so instead we can use a sink to capture the data and set a value
            .sink(receiveValue: { image in
                self.githubAvatarImageView.image = image
            })
        // convert the .sink to an `AnyCancellable` object that we have
        // referenced from the implied initializers
        avatarViewSubscriber = AnyCancellable(avatarViewSub)

        // KVO publisher of UIKit interface element
        let _ = repositoryCountLabel.publisher(for: \.text) <5>
            .sink { someValue in
                print("repositoryCountLabel Updated to \(String(describing: someValue))")
        }
    }

}
----
<1> We add a subscriber to our previous controller from that connects notifications of activity from the GithubAPI object to our activity indicator.
<2> Where the username is updated from the IBAction (from our earlier example <<#patterns-update-interface-userinput>>) we have the subscriber make the network request and put the results in a new variable (also <<reference.adoc#reference-published>>) on our ViewController.
<3> The first of two subscribers on the publisher `$githubUserData`, this pipeline extracts the count of repositories and updates the a UI label instance.
There is a bit of logic in the middle of the pipeline to return the string "unknown" when the list is empty.
<4> The second subscriber to the publisher `$githubUserData`, this triggers a follow on network request to request the image data for the github avatar.
This is a more complex pipeline, extracting the data from the githubUser, assembling a URL, and then requesting it.
As this code is in the ViewController, we can also use <<reference.adoc#reference-handleevents>> operator to trigger updates to the activityIndicator in our view.
We use <<reference.adoc#reference-subscribe>> to make the requests on a background queue, and later <<reference.adoc#reference-receive>> the results back onto the main thread to update the UI elements.
The <<reference.adoc#reference-catch>> and failure handling returns an empty `UIImage` instance in the event of failure.
<5> A final subscriber that doesn't do anything is attached to the UILabel itself.
Any Key-Value Observable object from Foundation can also produce a publisher.
In this example, we attach a publisher that triggers a print statement that the UI element was updated.

[NOTE]
====
While we could simply attach pipelines to UI elements as we're updating them, it more closely couples interactions to the actual UI elements themselves.
While easy and direct, it is often a good idea to make explicit state and updates to seperate out actions and data for debugging and understandability.
In the example above, we use two <<reference.adoc#reference-published>> properties to hold the state associated with the current view.
One of which is updated by an IBAction, and the second updated declaratively using a Combine publisher pipeline.
All other UI elements are updated publishers hanging from those properties getting updated.
====

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-future]
== Pattern 6.1: Wrapping an asynchronous call with a Future to create a one-shot publisher

__Goal__::

* Using Future to turn an an asynchronous call into publisher to use the result in a combine pipeline.

__References__::

* <<reference.adoc#reference-future>>

__See also__::

* <<#patterns-subject>>

__Code and explanation__::

[source, swift]
----
import Contacts
let futureAsyncPublisher = Future<Bool, Error> { promise in <1>
    CNContactStore().requestAccess(for: .contacts) { grantedAccess, err in <2>
        // err is an optional
        if let err = err { <3>
            promise(.failure(err))
        }
        return promise(.success(grantedAccess)) <4>
    }
}.eraseToAnyPublisher()
----

<1> Future itself has you define the return types and takes a closure.
It hands in a Result object matching the type description, which you interact.
<2> You can invoke the async API however is relevant, including passing in it's required closure.
<3> Within the completion handler, you determine what would cause a failure or a success. A call to `promise(.failure(<FailureType>))` returns the failure.
<4> Or a call to `promise(.success(<OutputType>))` returns a value.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-subject]
== Pattern 6.2: Wrapping an delegate based API using PassthroughSubject to create a repeating publisher

__Goal__::

* To use one of the Apple delegate APIs to provide values to be used in a combine pipeline.

__References__::

* <<reference.adoc#reference-passthroughsubject>>
* <<reference.adoc#reference-currentvaluesubject>>

__See also__::

* <<#patterns-future>>

__Code and explanation__::

[source, swift]
----

.eraseToAnyPublisher()
----


// force a page break - in HTML rendering is just a <HR>
<<<
'''
[#patterns-sequencing-async]
== Pattern 7: Coordinating a sequence of asynchronous operations

__Goal__::

* There are a variety of ways to chain together asynchronous operations.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

Combine adds to this variety, and is effective when you want to use the data from one operation as the input to the next.
If you are familiar with using Promises in another language, such as Javascript, this pattern is roughly the equivalent of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Chaining[Promise chaining].

The benefit to using Combine is that the sequencing can be relatively easy to parse visually.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-published]
== Pattern 8: Responding to updates in properties with @Published

__Goal__::

* @Published with properties and using read-only updates of those properties as publishing sources

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::


[source, swift]
----
@Published var username: String = ""

var validatedUsername: AnyPublisher<String?, Never> {
    return $username
        .debounce(for: 0.5, scheduler: RunLoop.main)
           //  <String?>|<Never>
        .removeDuplicates()
           //  <String?>|<Never>
        .flatMap { username in
            return Future { promise in
                self.usernameAvailable(username) { available in
                   promise(.success(available ? username : nil))
                }
          //    <Result<Output, Failure>>
            }
        }
          // <String?>|<Never>
        .eraseToAnyPublisher()
}
----

validation - listening for changes to validate them together

[source, swift]
----
@Published var password: String = ""
@Published var passwordAgain: String = ""

var validatedPassword: AnyPublisher<String?, Never> {
    return CombineLatest($password, $passwordAgain) { password, passwordAgain in
        guard password == passwordAgain, password.count > 8 else { return nil }
        return password
    }
      //  <String?>|<Never>
    .map { $0 == password1 ? nil : $0 }
      //  <String?>|<Never>
    .eraseToAnyPublisher()
      //  <String?>|<Never>
}
----

more complex validation - bringing together substreams

[source, swift]
----
var validatedCredentials: AnyPublisher<(String, String)?, Never> {
    return CombineLatest(validatedUsername, validatedPassword) { username, password in
        guard let uname = username, let pwd = password else { return nil }
        return (uname, pwd)
    }
    .eraseToAnyPublisher()
}

@IBOutlet var signupButton: UIButton!

var signupButtonStream: AnyCancellable?

override func viewDidLoad() {
    super.viewDidLoad()
    self.signupButtonStream = self.validatedCredentials
        .map { $0 != nil }
        .receive(on: RunLoop.main)
        .assign(to: \.isEnabled, on: signupButton)
}
----

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-notificationcenter]
== Pattern 9: Responding to updates from NotificationCenter

__Goal__::

* The big "master bus" of events across a variety of Apple platforms, its where you can listen for updates and changes from controls and events across a variety of frameworks.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

https://www.caseyliss.com/2019/6/18/quick-notes-on-yesterdays-post[Casey Liss talks about about this (not entirely happily)] based on the apple documentation https://developer.apple.com/documentation/combine/receiving_and_handling_events_with_combine[Receiving and Handling Events with Combine].

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-bindableobject]
== Pattern 10: Using BindableObject with SwiftUI models as a publisher source

__Goal__::

* SwiftUI includes @Binding and the BindableObject protocol, which provides a publishing source to alerts to model objects changing.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

// REF/EXAMPLE OF ANOTHER WRITER https://mecid.github.io/2019/06/19/building-forms-with-swiftui/
// REF/EXAMPLE OF ANOTHER WRITER https://mecid.github.io/2019/07/03/managing-data-flow-in-swiftui/

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-testing-pipeline]
== Pattern N.1: Testing pipelines

__Goal__::

* For testing what's happening in a pipeline

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::



* use a Subject -> pipeline -> sink()
* set up a sink to collect value
* drive values through the pipeline with Subject.send()
* assert results after the sink has processed them

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-testing-publisher]
== Pattern N.2: Testing a publisher

__Goal__::

* For testing a publisher (and any pipeline attached)

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

* set up an expectation (`XCTestExpectation`)
* create your publisher & relevant pipeline if so desired
* create a sink to capture the results that works on both completions and values
** this can be separate, or just chained to the pipeline, depending on what makes most sense to you
* `wait` on the expectation to let the test "do it's thing" in the background

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-testing-subscriber]
== Pattern N.3: Testing a subscriber

__Goal__::

* For testing a subscriber (how it reacts):

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

* set up your subscriber and any pipeline leading to it
* use a Subject to "inject" values
* test the results after the value is sent
* if the updates include some async/background work before data is available, use an expectation
** add a callback to the async pieces where you can trigger the expectation, and do your asserts just prior to fulfilling the expectation

& of course you can always test using UITesting - spinning up your whole app, initializing state, and then driving and verifying the results.

__(Uncertain)__ Mocking or faking a publisher (such as dataTaskPublisher) to validate things like using `retry()` operator
* might be able to use a `Publishers.Future()`, expose as an AnyPublisher() (do the same with dataTaskPublisher) to make the the same - and in your setup, inject in the one you want to use.
** Instrument the Future() closure to record what gets called, and maybe set it up to return an explicit set of responses.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-debugging]
== Pattern N+1: Debugging pipelines

__Goal__::

* For testing a subscriber (how it reacts):

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

. use print() and/or print("prefixValue") to get console output of what's happening in the pipeline lifecycle
  * create a .sink() to capture results, and drive it with a PassthroughSubject for specific control

. add a handleEvents() operator
  * create closures to do additional poking at values or digging into more structured pieces than get exposed with a print()
  * allows you to ignore some sections you don't care about
  * closures on `receiveSubscription`, `receiveRequest`, `receiveCancel`, `receiveOutput`, and `receiveCompletion`

. breakPoint
  * if you want to break into a debugger, add in a closure that returns true and you can inspect to your heart's content
  ** closure's on `receiveSubscription`, `receiveOutput`, and `receiveCompletion`

  * might also be interesting to use breakpointOnError() which triggers only when a failure completion


// force a page break - in HTML rendering is just a <HR>
<<<
'''
