[#patterns]
= Patterns and Recipes

Included are a series of patterns and examples of Publishers, Subscribers, and pipelines.
These examples are meant to illustrate how to use the Combine framework to accomplish various tasks.

[NOTE]
====
__Since this is a work in progress:__
if you have a suggestion for a pattern or recipe, I'm happy to consider it.

Please https://github.com/heckj/swiftui-notes/issues/new/choose[Open an issue] in GitHub to request something.
====

[#patterns-sink-subscriber]
== Pattern 1.1: Creating a subscriber with sink

__Goal__::

* To receive the output, and the errors or completion messages, generated from a publisher or through a pipeline, you can create a subscriber with `sink`.

__References__::

* <<reference.adoc#reference-sink>>

__See also__::

* <<#patterns-assign-subscriber>>
* <<#patterns-testing-publisher>>
* <<#patterns-testing-pipeline>>

__Code and explanation__::

Sink creates an all-purpose subscriber to capture or react the data from a Combine pipeline, while also supporting cancellation and the <<coreconcepts.adoc#core-lifecycle,publisher subscriber lifecycle>>.

.simple sink
[source, swift]
----
let cancellablePipeline = publishingSource.sink { someValue in <1>
    // do what you want with the resulting value passed down
    // be aware that depending on the data type being returned, you may get this closure invoked
    // multiple times.
    print(".sink() received \(someValue)")
})
----
<1> The simple version of a sink is very compact, with a single trailing closure that only receives data when presented through the pipeline.

.sink with completions and data
[source, swift]
----
let cancellablePipeline = publishingSource.sink(receiveCompletion: { completion in <1>
    switch completion {
    case .finished:
        // no associated data, but you can react to knowing the request has been completed
        break
    case .failure(let anError):
        // do what you want with the error details, presenting, logging, or hiding as appropriate
        print("received the error: ", anError)
        break
    }
}, receiveValue: { someValue in
    // do what you want with the resulting value passed down
    // be aware that depending on the data type being returned, you may get this closure invoked
    // multiple times.
    print(".sink() received \(someValue)")
})

cancellablePipeline.cancel() <2>
----

<1> Sinks are created by chaining the code from a publisher or pipeline, and terminate the pipeline.
When the sink is created or invoked on a publisher, it implicitly starts <<coreconcepts.adoc#core-lifecycle,the lifecycle>> with the `subscribe` and will request unlimited data.
<2> Creating a sink is cancellable subscriber, so at any time you can take the reference that terminated with sink and invoke `.cancel()` on it to invalidate and shut down the pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-assign-subscriber]
== Pattern 1.2: Creating a subscriber with assign

__Goal__::

* To use the results of a pipeline to set a value, often a property on a user interface view or control, but any KVO compliant object can be the target

__References__::

* <<reference.adoc#reference-assign>>
* <<reference.adoc#reference-receive>>

__See also__::

* <<#patterns-sink-subscriber>>

__Code and explanation__::

Assign is a subscriber that's specifically designed to apply data from a publisher or pipeline into a property, updating that property whenever it receives data.
Like sink, it activates when created and requests an unlimited data updates.
Assign requires the failure type to be specified as `<Never>`, so if your pipeline could fail (such as using an operator like tryMap) you will need to <<#patterns-general-error-handling,convert or handle the the failure cases>> before using `.assign`.

.simple sink
[source, swift]
----
let cancellablePipeline = publishingSource <1>
    .receive(on: RunLoop.main) <2>
    .assign(to: \.isEnabled, on: yourButton) <3>

cancellablePipeline.cancel() <4>
----

<1> `.assign` is typically chained onto a publisher when you create it, and the return value is cancellable.
<2> If `.assign` is being used to update a user interface element, you need to make sure that it is being updated on the main thread. This call makes sure the subscriber is received on the main thread.
<3> Assign references the property being updated using a https://developer.apple.com/documentation/swift/referencewritablekeypath[key path], and a reference to the object being updated.
<4> At any time you can can to terminate and invalidate pipelines with cancel(). Frequently, you cancel the pipelines when you deactivate the objects (such as a viewController) that are getting updated from the pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-dataTaskPublisher-decode]
== Pattern 2.1: Making a network request with dataTaskPublisher

__Goal__::

* One of the common use cases is requesting JSON data from a URL and decoding it.

__References__::

* <<reference.adoc#reference-dataTaskPublisher>>
* <<reference.adoc#reference-map>>
* <<reference.adoc#reference-decode>>
* <<reference.adoc#reference-sink>>
* <<reference.adoc#reference-subscribe>>

__See also__::

* <<#patterns-dataTaskPublisher-tryMap>>
* <<#patterns-oneshot-error-handling>>
* <<#patterns-retry>>

__Code and explanation__::

This can be readily accomplished with Combine using
<<reference.adoc#reference-dataTaskPublisher>> followed by a series of operators that process the
data.
Minimally, this is <<reference.adoc#reference-map>> and <<reference.adoc#reference-decode>> before going into your subscriber.

https://developer.apple.com/documentation/foundation/urlsession/3329708-datataskpublisher[dataTaskPublisher] on https://developer.apple.com/documentation/foundation/urlsession[URLSession].

The simplest case of using this might be:

[source, swift]
----
let myURL = URL(string: "https://postman-echo.com/time/valid?timestamp=2016-10-10")
// checks the validity of a timestamp - this one returns {"valid":true}
// matching the data structure returned from https://postman-echo.com/time/valid
fileprivate struct PostmanEchoTimeStampCheckResponse: Decodable, Hashable { <1>
    let valid: Bool
}

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!) <2>
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .map { $0.data } <3>
    .decode(type: PostmanEchoTimeStampCheckResponse.self, decoder: JSONDecoder()) <4>

let cancellableSink = remoteDataPublisher.sink
    .sink(receiveCompletion: { completion in
            print(".sink() received the completion", String(describing: completion))
            switch completion {
                case .finished: <5>
                    break
                case .failure(let anError): <6>
                    print("received error: ", anError)
            }
    }, receiveValue: { someValue in <7>
        print(".sink() received \(someValue)")
    })
----

<1> Commonly you'll have a struct defined that supports at least https://developer.apple.com/documentation/swift/decodable[Decodable] (if not the full https://developer.apple.com/documentation/swift/codable[Codable protocol]). This struct can be defined to only pull the pieces you're interested in from the JSON provided over the network.
<2> dataTaskPublisher is instantiated from URLSession. You can configure your own options on URLSession, or use the general shared session as you require.
<3> The data that is returns down the pipeline is a tuple: `(data: Data, response: URLResponse)`. The <<reference.adoc#reference-map>> operator is used to get the data and drop the URL response, returning just Data down the pipeline.
<4> <<reference.adoc#reference-decode>> is used to load the data and attempt to transform it into the struct defined. Decode can throw an error itself if the decode fails. If it succeeds, the object passed down the pipeline will be the struct from the JSON data.
<5> If the decoding happened without errors, the finished completion will be triggered, and the value will also be passed to the receiveValue closure.
<6> If the a failure happened (either with the original network request or the decoding), the error will be passed into with the `.failure` completion.
<7> Only if the data succeeded with request and decoding will this closure get invoked, and the data format received with be an instance of the struct `PostmanEchoTimeStampCheckResponse`.

[#patterns-dataTaskPublisher-tryMap]
== Pattern 2.2: Stricter request processing with dataTaskPublisher

__Goal__::

* If URLSession is handing back a result that you want to intepret more strictly, for example, to trigger an error from a successful network request, you can use tryMap along with the decoding sequence.

__References__::

* <<reference.adoc#reference-dataTaskPublisher>>
* <<reference.adoc#reference-tryMap>>
* <<reference.adoc#reference-decode>>
* <<reference.adoc#reference-sink>>
* <<reference.adoc#reference-subscribe>>

__See also__::

* <<#patterns-dataTaskPublisher-decode>>
* <<#patterns-oneshot-error-handling>>
* <<#patterns-retry>>


__Code and explanation__::

To have more control over what is considered a failure in the URL response, use a `tryMap` operator on the tuple response from dataTaskPublisher.
An example of that might look like:

[source, swift]
----
let myURL = URL(string: "https://postman-echo.com/time/valid?timestamp=2016-10-10")
// checks the validity of a timestamp - this one returns {"valid":true}
// matching the data structure returned from https://postman-echo.com/time/valid
fileprivate struct PostmanEchoTimeStampCheckResponse: Decodable, Hashable {
    let valid: Bool
}
enum testFailureCondition: Error {
    case invalidServerResponse
}


let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    .tryMap { data, response -> Data in <1>
                guard let httpResponse = response as? HTTPURLResponse, <2>
                    httpResponse.statusCode == 200 else { <3>
                        throw testFailureCondition.invalidServerResponse <4>
                }
                return data <5>
    }
    .decode(type: PostmanEchoTimeStampCheckResponse.self, decoder: JSONDecoder())

let cancellableSink = remoteDataPublisher.sink
    .sink(receiveCompletion: { completion in
            print(".sink() received the completion", String(describing: completion))
            switch completion {
                case .finished:
                    break
                case .failure(let anError):
                    print("received error: ", anError)
            }
    }, receiveValue: { someValue in
        print(".sink() received \(someValue)")
    })
----

Where the <<#patterns-dataTaskPublisher-decode, previous pattern>> used a <<reference.adoc#reference-map>> operator, this uses tryMap, which allows us to identify and throw errors in the pipeline based on what was returned.

<1> <<reference.adoc#reference-tryMap>> still gets the tuple of `(data: Data, response: URLResponse)`, and is defined here as returning just the type of Data down the pipeline.
<2> Within the closure for tryMap, we can cast the response to HTTPURLResponse and dig deeper into it, including looking at the specific status code.
<3> In this case, we want to consider **anything** other than a 200 response code as a failure.
<4> If the predicates aren't met, then we can throw an instance of an error of our choosing, `invalidServerResponse` in this case.
<5> If no error has occured, then we simply pass down Data for further processing.

When an error is triggered on the pipeline, a `.failure` completion is sent with the error encapsulated within it, regardless of where it happened in the pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-general-error-handling]
== Error Handling

The examples above expected that the subscriber would handle the error conditions, if they occured.
However, you are not always able to control the subscriber - as might be the case if you're using SwiftUI view properties as the subscriber, and you're providing the publisher.
In these cases, you need to build your pipeline so that the output types match the subscriber types.

For example, if you are working with SwiftUI and the you want to use `.assign` to set the `isEnabled` property on a button, the subscriber will have a few requirements:

. the subcriber should match the type output of `<Bool>`, `<Never>`
. the subscriber should be called on the main thread

With a publisher that can throw an error (such as `dataTaskPublisher`), you need to construct a pipeline to convert the output type, but also handle the error within the pipeline to match a failure type of `<Never>`.

How you handle the errors within a pipeline is very dependent on how the pipeline is working.
If the pipeline is set up to return a single result and terminate, continue to <<patterns-oneshot-error-handling>>.
If the pipeline is set up to continually update, the error handling needs to be a little more complex.
Jump ahead to <<patterns-continual-error-handling>>.

[#patterns-assertNoFailure]
=== Pattern 3.1: converting to a Never failure type using assertNoFailure

__Goal__::

* Verify no error has occured within a pipeline

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

A brutal way to handle this is to crash the application when an error happens.
Combine provides the operator `assertNoFailure()` for this purpose.
This is useful if you are sure you handled the errors and need to map a pipeline which technically can generate a failure type of `<Error>` to a subscriber that requires a failure type of `<Never>`.

Adding it into the pipeline requires no additional parameters, but you can include a string:

[source, swift]
----
.assertNoFailure()
// OR
.assertNoFailure("What could possibly go wrong?")
----

[NOTE]
====
I'm not entirely clear on where that string would appear if you did include it.

When trying out this code in unit tests, the tests invariably drop into a debugger at the assertion point when a .failure is processed through the pipeline.
====

It is far more likely that you want to handle the error and not have the application crash.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-oneshot-error-handling]
=== Pattern 3.2: Using catch to handle errors in a one-shot pipeline

__Goal__::

* The `.catch()` operator is useful to recover from an error, but it can have unexpected side effects if you aren't familiar with how it works.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

`.catch()` handles errors by replacing the upstream publisher with another publisher that you provide as a return in a closure.
This effectively terminates the earlier portion of the pipeline.
If you're using a one-shot publisher (one that doesn't create more than a single event), then this is fine.

For example, dataTaskPublisher is a one-shot publisher, and you might use catch with it to ensure that you get a response, returning a placeholder in the event of an error.
Extending our previous example to provide a default response:

[source, swift]
----
struct IPInfo: Codable {
    // matching the data structure returned from ip.jsontest.com
    var ip: String
}
let myURL = URL(string: "http://ip.jsontest.com")
// NOTE(heckj): you'll need to enable insecure downloads in your Info.plist for this example
// since the URL scheme is 'http'

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .map({ (inputTuple) -> Data in
        return inputTuple.data
    })
    .decode(type: IPInfo.self, decoder: JSONDecoder())
    .catch { err in
        return Publishers.Just(IPInfo(ip: "8.8.8.8"))
    }
    .eraseToAnyPublisher()
----

// NOTE(heckj): this next bit (until retry) might be better migrated to the reference section on how catch works.

A possible problem with this technique is that the if the original publisher generates more values to which you wish to react, the original pipeline has been ended.
This means if you are creating a pipeline that reacts to a `@Published` property, then after any failed value that activates the catch operator, the pipeline will cease to react further.
See <<reference.adoc#reference-catch>> for more detail and an example.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-retry]
=== Pattern 3.3: Retrying in the event of a temporary failure

__Goal__::

* The `retry` operator can be included in a chain to retry a subscription when a `.failure` completion occurs.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

When you specify this operator in a pipeline and it receives a subscription, it first tries to request a subscription from it's upstream publisher.
If the response to that subscription fails, then it will retry the subscription to the same publisher.

The retry operator can be specified with a number of retries to attempt.
If no number of retries is specified, it will attempt to retry indefinitely until it receives a .finished completion from it's subscriber.
If the number of retries is specified and all requests fail, then the `.failure` completion is passed down to the subscriber of this operator.

In practice, this is mostly commonly desired when attempting to request network resources with an unstable connection.
If you use a retry operator, you should add a specific number of retries so that the subscription doesn't effectively get into an infinite loop.

An example of the above example using retry:

[source, swift]
----
struct IPInfo: Codable {
    // matching the data structure returned from ip.jsontest.com
    var ip: String
}
let myURL = URL(string: "http://ip.jsontest.com")
// NOTE(heckj): you'll need to enable insecure downloads in your Info.plist for this example
// since the URL scheme is 'http'

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .retry(3)
    // if the URLSession returns a .failure completion, try at most 3 times to get a successful response
    .map({ (inputTuple) -> Data in
        return inputTuple.data
    })
    .decode(type: IPInfo.self, decoder: JSONDecoder())
    .catch { err in
        return Publishers.Just(IPInfo(ip: "8.8.8.8"))
    }
    .eraseToAnyPublisher()
----

[WARNING]
====
When using the `retry()` operator with `dataTaskPublisher`, verify that the URL you are requesting isn't going to have negative side effects if requested repeatedly or with a retry.
Ideally such requests are be expected to be idempotent.
====

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-continual-error-handling]
=== Pattern 3.4: Using flatMap with catch to handle errors

__Goal__::

* The `flatMap` operator can be used with `catch` to continue to handle errors on new published values.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

The `flatMap()` operator is exactly what we need in this use case.

You can think of the `flatMap()` operator as a way to inject values into your pipeline from a temporary one-shot publisher.
For every element `flatMap()` receives, it invokes it's closure to create a publisher.
That publisher is then sending values to any downstream subscriber.

This is a perfect mechanism for when you want to maintain updates up an upstream publisher, as it effectively creates one-shot publishers (or even small pipelines) that send a single value and then complete.
The completion from the created one-shot publishers terminates in the flatMap and isn't passed to downstream subscribers.
To use this with error handling, we can create a one-shot publisher, or pipeline, that starts with the value provided upstream.
Then we create the pipeline to do any potentially failing work, and construct it with a `.catch` as we saw earlier to provide a fallback value.

A diagram version of this pipelines might be:

[source]
----
     one-shot-publisher(value) -> catch ( fallback )      // <- one-shot pipeline
                          ^                        \
                          |                         \
publisher -> flatMap -> ( +                           +  ) -> subscriber
----

In swift, this looks like:

[source, swift]
----
.flatMap { data in
    return Just(data)
    .decode(YourType.self, JSONDecoder())
    .catch {
        return Just(YourType.placeholder)
    }
}
----

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-constrained-network]
== Pattern 4: Requesting data from an alternate URL when the network is constrained

__Goal__::

* From Apple's WWDC 19 presentation https://developer.apple.com/videos/play/wwdc2019/712/[Advances in Networking, Part 1], a sample pattern was provided using `.tryCatch` and `.tryMap` operators to react to the specific error of having the network be constrained.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::


[NOTE]
====
This sample is originally from the WWDC session, but the API and example is evolving with the beta releases of Combine since that presentation.
`tryCatch` was missing in the Beta2 release, and has returned in beta3.
====

[source, swift]
----
// Generalized Publisher for Adaptive URL Loading
func adaptiveLoader(regularURL: URL, lowDataURL: URL) -> AnyPublisher<Data, Error> {
    var request = URLRequest(url: regularURL)
    request.allowsConstrainedNetworkAccess = false
    return URLSession.shared.dataTaskPublisher(for: request)
        .tryCatch { error -> URLSession.DataTaskPublisher in
            guard error.networkUnavailableReason == .constrained else {
               throw error
            }
            return URLSession.shared.dataTaskPublisher(for: lowDataURL)
        .tryMap { data, response -> Data in
            guard let httpResponse = response as? HTTPUrlResponse,
                   httpResponse.status_code == 200 else {
                       throw MyNetworkingError.invalidServerResponse
            }
            return data
}
.eraseToAnyPublisher()
----

In the sample, if the error returned from the original request wasn't an issue of the network being constrained, it passes on the .failure completion down the pipeline.
If the error is that the network is constrained, then the tryCatch operator creates a new request to an alternate URL.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-update-interface-network-request]
== Pattern 5: Update the status of your interface from a network request

__Goal__::

* Querying a web based API and returning the data to be displayed in your UI

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

Below is a contrived example where you want to make a network to check for the username availability that you are watching with `@Published`.
As the property `username` is updated, you want to check to see if the updated username is available.

This contrived example expects that you have a web service that you can query, which will return a structured response in JSON.

[source, swift]
----
@Published var username: String = ""

struct UsernameResponse: Codable {
    username: String
    available: Bool
}

var validatedUsername: AnyPublisher<String?, Never> {
    return $username
        .debounce(for: 0.5, scheduler: RunLoop.main)
        .removeDuplicates()
        .flatMap { username in
            let constructedURL = URL(string: "https://yourhost.com/?user=\(username)")
            return remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: constructedURL!)
                .map({ (inputTuple) -> Data in
                    return inputTuple.data
                })
                .decode(type: UsernameResponse.self, decoder: JSONDecoder())
                .map { response: UsernameResponse in
                    return response.available
                }
                .catch { err in
                    // if the service is down, or the JSON malformed, return a false response
                    return Publishers.Just(False))
                }
        }
}
----

In the example above, for every update into .flatMap() we are creating a request to check and parse for the availability from the service.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-future]
== Pattern 6: Wrapping an asynchronous call with a Future

__Goal__::

* Using Future to turn an an asynchronous call into publisher

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::


[source, swift]
----

let myPublisher = Publishers.Future { promise in
    asyncFunctionWithACompletion(inputValue) { outputValue in
        promise(.success(outputValue ? inputValue : nil))
    }
}
.eraseToAnyPublisher()
----

This setup can be used to inline just about anything into a Combine pipeline.

possible example:
- take periodic frame updates from the camera and run them into the Vision framework to ask if there's a bar code, and if so, retrieve it and display its info

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-sequencing-async]
== Pattern 7: Coordinating a sequence of asynchronous operations

__Goal__::

* There are a variety of ways to chain together asynchronous operations.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

Combine adds to this variety, and is effective when you want to use the data from one operation as the input to the next.
If you are familiar with using Promises in another language, such as Javascript, this pattern is roughly the equivalent of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Chaining[Promise chaining].

The benefit to using Combine is that the sequencing can be relatively easy to parse visually.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-published]
== Pattern 8: Responding to updates in properties with @Published

__Goal__::

* @Published with properties and using read-only updates of those properties as publishing sources

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::


[source, swift]
----
@Published var username: String = ""

var validatedUsername: AnyPublisher<String?, Never> {
    return $username
        .debounce(for: 0.5, scheduler: RunLoop.main)
           //  <String?>|<Never>
        .removeDuplicates()
           //  <String?>|<Never>
        .flatMap { username in
            return Future { promise in
                self.usernameAvailable(username) { available in
                   promise(.success(available ? username : nil))
                }
          //    <Result<Output, Failure>>
            }
        }
          // <String?>|<Never>
        .eraseToAnyPublisher()
}
----

validation - listening for changes to validate them together

[source, swift]
----
@Published var password: String = ""
@Published var passwordAgain: String = ""

var validatedPassword: AnyPublisher<String?, Never> {
    return CombineLatest($password, $passwordAgain) { password, passwordAgain in
        guard password == passwordAgain, password.count > 8 else { return nil }
        return password
    }
      //  <String?>|<Never>
    .map { $0 == password1 ? nil : $0 }
      //  <String?>|<Never>
    .eraseToAnyPublisher()
      //  <String?>|<Never>
}
----

more complex validation - bringing together substreams

[source, swift]
----
var validatedCredentials: AnyPublisher<(String, String)?, Never> {
    return CombineLatest(validatedUsername, validatedPassword) { username, password in
        guard let uname = username, let pwd = password else { return nil }
        return (uname, pwd)
    }
    .eraseToAnyPublisher()
}

@IBOutlet var signupButton: UIButton!

var signupButtonStream: AnyCancellable?

override func viewDidLoad() {
    super.viewDidLoad()
    self.signupButtonStream = self.validatedCredentials
        .map { $0 != nil }
        .receive(on: RunLoop.main)
        .assign(to: \.isEnabled, on: signupButton)
}
----

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-notificationcenter]
== Pattern 9: Responding to updates from NotificationCenter

__Goal__::

* The big "master bus" of events across a variety of Apple platforms, its where you can listen for updates and changes from controls and events across a variety of frameworks.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

https://www.caseyliss.com/2019/6/18/quick-notes-on-yesterdays-post[Casey Liss talks about about this (not entirely happily)] based on the apple documentation https://developer.apple.com/documentation/combine/receiving_and_handling_events_with_combine[Receiving and Handling Events with Combine].

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-bindableobject]
== Pattern 10: Using BindableObject with SwiftUI models as a publisher source

__Goal__::

* SwiftUI includes @Binding and the BindableObject protocol, which provides a publishing source to alerts to model objects changing.

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

// REF/EXAMPLE OF ANOTHER WRITER https://mecid.github.io/2019/06/19/building-forms-with-swiftui/
// REF/EXAMPLE OF ANOTHER WRITER https://mecid.github.io/2019/07/03/managing-data-flow-in-swiftui/

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-testing-pipeline]
== Pattern N.1: Testing pipelines

__Goal__::

* For testing what's happening in a pipeline

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::



* use a Subject -> pipeline -> sink()
* set up a sink to collect value
* drive values through the pipeline with Subject.send()
* assert results after the sink has processed them

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-testing-publisher]
== Pattern N.2: Testing a publisher

__Goal__::

* For testing a publisher (and any pipeline attached)

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

* set up an expectation (`XCTestExpectation`)
* create your publisher & relevant pipeline if so desired
* create a sink to capture the results that works on both completions and values
** this can be separate, or just chained to the pipeline, depending on what makes most sense to you
* `wait` on the expectation to let the test "do it's thing" in the background

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-testing-subscriber]
== Pattern N.3: Testing a subscriber

__Goal__::

* For testing a subscriber (how it reacts):

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

* set up your subscriber and any pipeline leading to it
* use a Subject to "inject" values
* test the results after the value is sent
* if the updates include some async/background work before data is available, use an expectation
** add a callback to the async pieces where you can trigger the expectation, and do your asserts just prior to fulfilling the expectation

& of course you can always test using UITesting - spinning up your whole app, initializing state, and then driving and verifying the results.

__(Uncertain)__ Mocking or faking a publisher (such as dataTaskPublisher) to validate things like using `retry()` operator
* might be able to use a `Publishers.Future()`, expose as an AnyPublisher() (do the same with dataTaskPublisher) to make the the same - and in your setup, inject in the one you want to use.
** Instrument the Future() closure to record what gets called, and maybe set it up to return an explicit set of responses.

// force a page break - in HTML rendering is just a <HR>
<<<
'''

[#patterns-debugging]
== Pattern N+1: Debugging pipelines

__Goal__::

* For testing a subscriber (how it reacts):

__References__::

* << link to reference pages>>

__See also__::

* << link to other patterns>>

__Code and explanation__::

. use print() and/or print("prefixValue") to get console output of what's happening in the pipeline lifecycle
  * create a .sink() to capture results, and drive it with a PassthroughSubject for specific control

. add a handleEvents() operator
  * create closures to do additional poking at values or digging into more structured pieces than get exposed with a print()
  * allows you to ignore some sections you don't care about
  * closures on `receiveSubscription`, `receiveRequest`, `receiveCancel`, `receiveOutput`, and `receiveCompletion`

. breakPoint
  * if you want to break into a debugger, add in a closure that returns true and you can inspect to your heart's content
  ** closure's on `receiveSubscription`, `receiveOutput`, and `receiveCompletion`

  * might also be interesting to use breakpointOnError() which triggers only when a failure completion


// force a page break - in HTML rendering is just a <HR>
<<<
'''
