name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: Show what's in Applications
      run: ls -al /Applications

    - name: "switch to Xcode version 11.3"
      run: sudo xcode-select -s /Applications/Xcode_11.3.app

    - name: xcodebuild --help
      run: xcodebuild --help

    - name: xcodebuild --showsdks
      run: xcodebuild -showsdks

    - name: xcodebuild -showBuildSettings
      run: xcodebuild -showBuildSettings

    # - name: xcodebuild -showTestPlans
    #   run: xcodebuild -showTestPlans

    - name: xcodebuild -list
      run: xcodebuild -list

    - name: Show available destinations
      run: xcodebuild -scheme SwiftUI-Notes -showdestinations

    - name: Run the Combine test suite
      run: |
        xcodebuild -scheme SwiftUI-Notes \
        -configuration Debug \
        -sdk iphonesimulator13.3 \
        -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 8' \
        test -showBuildTimingSummary
