name: CI

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: experiment1
        uses: asciidoctor/docker-asciidoctor
        with:
          entrypoint: /bin/echo
          args: The ${{ github.event_name }} event triggered this step.
            
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: Show what's in Applications
      run: ls -al /Applications

    - name: "switch to Xcode version 11.4"
      run: sudo xcode-select -s /Applications/Xcode_11.4.app

    - name: xcodebuild --help
      run: xcodebuild --help

    - name: xcodebuild --showsdks
      run: xcodebuild -showsdks

    - name: xcodebuild -showBuildSettings
      run: xcodebuild -showBuildSettings

    # - name: xcodebuild -showTestPlans
    #   run: xcodebuild -showTestPlans

    - name: xcodebuild -list
      run: xcodebuild -list

    - name: Show available destinations
      run: xcodebuild -scheme SwiftUI-Notes -showdestinations

    - name: Run the Combine test suite
      run: |
        xcodebuild -scheme SwiftUI-Notes \
        -configuration Debug \
        -sdk iphonesimulator13.4 \
        -destination 'platform=iOS Simulator,OS=13.4,name=iPhone 8' \
        test -showBuildTimingSummary
